var ShlokHeader = ["C]\\ H[ T[ DFZF CNIG[ lJQF[ zLS\'Q6"];
ShlokHeader.push("VG[ J\'tTF,I UFDG[ lJQF[ ZCIF V[JF");
ShlokHeader.push("zL WD\"N[J YSL K[ HgD H[DGM V[JF");
ShlokHeader.push("TYF VDFZF VFlzT V[JF H[ D]S]\\NFG\\N");
ShlokHeader.push("TYF VDFZ[ VFlzT H[ ;]JFl;GL VG[");
ShlokHeader.push("V[ ;J[\" T[D6[ 5MTFGF WD\"GL Z1FFGF");
ShlokHeader.push("VG[ VF lX1FF5+L ,bIFG]\\ H[ SFZ6");
ShlokHeader.push("VG[ zLDN= EFUJT 5]ZF6 VFlNS H[");
ShlokHeader.push("VG[ T[ ;NFRFZG]\\ p&LT;,\\3G SZLG[ H[ DG]QI");
ShlokHeader.push("T[ DF8[ VDFZF lXQI V[JF H[ TD[ ;J[\"");
ShlokHeader.push("CJ[ T[ JtIF\"GL ZLT SCLV[ KLV[ H[");
ShlokHeader.push("VG[ N[JTF VG[ l5T\' T[GF\\ I7G[ VY[\"");
ShlokHeader.push("VG[ :+L4 WG VG[ ZFHI T[GL 5|Fl%TG[");
ShlokHeader.push("VG[ VFtD3FT TM TLY\"G[ lJQF[ 56 G");
ShlokHeader.push("VG[ H[ DF\\; K[ T[ TM I7G]\\ X[QF CMI");
ShlokHeader.push("VG[ SIFZ[S 5MTFJT[ SF\\.S VIMuI");
ShlokHeader.push("VG[ WD\" SZJFG[ VY[\" 56 VDFZF");
ShlokHeader.push("VG[ VDFZF VFlzT H[ 5]~QF TYF");
ShlokHeader.push("VG[ H[GF CFYG]\\ ZF\\W[, VgG TYF H[GF");
ShlokHeader.push("VG[ 5MTFGF :JFY\"GL l;lwWG[ VY[\" 56");
ShlokHeader.push("VG[ N[JTF4 TLY\"4 A|FCD64 5lTJ|TF4 ;FW]");
ShlokHeader.push("VG[ H[ N[JTFG[ ;]ZF VG[ DF\\;G]\\ G{J[n");
ShlokHeader.push("VG[ DFU\"G[ lJQF[ RF,T[ lXJF,IFlNS H[");
ShlokHeader.push("VG[ 5MT5MTFGF J6F\"zDGM H[ WD\"");
ShlokHeader.push("VG[ H[GF JRGG[ ;F\\E/J[ SZLG[ zLS\'Q6");
ShlokHeader.push("VG[ H[ ;tI JRG AM,J[ SZLG[ 5MTFGM");
ShlokHeader.push("VG[ RMZ4 5F5L4 jI;GL4 5FB\\0L4 SFDL");
ShlokHeader.push("VG[ H[ DG]QI ElSTG]\\ VYJF 7FGG]\\");
ShlokHeader.push("VG[ H[ XF:+G[ lJQF[ zLS\'Q6 EUJFG");
ShlokHeader.push("VG[ UF?IF lJGFG]\\ H[ H/ TYF N}W");
ShlokHeader.push("VG[ H[ VF{QFW NF~ TYF DF\\; T[6[");
ShlokHeader.push("VG[ ,MS G[ XF:+ T[D6[ D/D}+");
ShlokHeader.push("VG[ RMZ DFU[\" SZLG[ 5[;J]\\ GlC VG[");
ShlokHeader.push("VG[ VDFZF ;t;\\UL H[ 5]~QF DF+");
ShlokHeader.push("VG[ U]~G]\\ V5DFG G SZJ]\\ TYF H[");
ShlokHeader.push("VG[ lJRFIF\" lJGF TtSF/ SM. SFI\" G");
ShlokHeader.push("VG[ U]~4 N[J VG[ ZFHF V[ +6GF NX\"GG[");
ShlokHeader.push("VG[ H[ J:+ 5C[I[\" YS[ 5MTFGF\\ V\\U");
ShlokHeader.push("VG[ zLS\'Q6 EUJFGGL H[ ElST T[");
ShlokHeader.push("VG[ pt;JGF lNJ;G[ lJQF[ TYF lGtI 5|tI[");
ShlokHeader.push("VG[ WD\"J\\XL U]~ YSL zLS\'Q6 EUJFGGL");
ShlokHeader.push("VG[ T[ lT,S H[ T[ UM5LR\\NG[ SZLG[");
ShlokHeader.push("VG[ T[ lT,SGF DwIG[ lJQF[ H UM/");
ShlokHeader.push("VG[ 5MTFGF WD\"G[ lJQF[ ZCIF VG[ zLS\'Q6GF");
ShlokHeader.push("VG[ T[ ;rK]N| YSL ALHF H[ HFlTV[");
ShlokHeader.push("VG[ H[ A|FCD6FlNSG[ l+5]\\0= H[ VF0]\\ lT,S");
ShlokHeader.push("VG[ GFZFI6 VG[ lXJHL V[ A[IG]\\");
ShlokHeader.push("VG[ VDFZF VFlzT H[ DG]QI T[D6[");
ShlokHeader.push("VG[ VDFZF ;t;\\UL T[D6[ lGtI ;}I\"");
ShlokHeader.push("VG[ 5KL V[S :YFGSG[ lJQF[ A[;LG[");
ShlokHeader.push("VG[ T[ JFZ 5KL 5lJ+ 5\'yJLG[ lJQF[");
ShlokHeader.push("VG[ 5KL ;t;\\UL 5]~QFDF+G[ RF\\N,[");
ShlokHeader.push("VG[ T[ lJWJF :+LVF[ DF+G[ 5MTFGF");
ShlokHeader.push("VG[ T[ 5KL zLZFWFS\'Q6GL H[ lR+");
ShlokHeader.push("VG[ H[ VDFZF ;t;\\ULDF\\ V\\AZLQF");
ShlokHeader.push("VG[ T[ H[ VFtDlGJ[NL EST T[D6[");
ShlokHeader.push("VG[ T[ 5KL zLS\'Q6 EUJFGGF H[");
ShlokHeader.push("VG[ 5KL zLS\'Q6 EUJFGG[ G{J[n");
ShlokHeader.push("VG[ lGU]\"6 SC[TF DFIFGF H[ ;tJFlNS");
ShlokHeader.push("VG[ V[ H[ VFtDlGJ[NL EST T[D6[");
ShlokHeader.push("VG[ J/L ;J[\" H[ VDFZF ;t;\\UL T[D6[");
ShlokHeader.push("VG[ H[ zLS\'Q6G]\\ :J~5 5MTFG[ ;[JJFG[");
ShlokHeader.push("VG[ VDFZF H[ ;J[\" ;t;\\UL T[D6[ lGtI");
ShlokHeader.push("VG[ T[ zLS\'Q6GL H[ SYFJFTF\" T[ 5ZD");
ShlokHeader.push("VG[ VDFZF VFlzT H[ ;J[\" ;t;\\UL");
ShlokHeader.push("VG[ H[ DG]QI H[JF U]6[ SZLG[ I]ST");
ShlokHeader.push("VG[ 5MTFGF H[ ;[JS CMI4 T[ ;J\"GL");
ShlokHeader.push("VG[ H[ 5]~QF H[JF U]6JF/M CMI T[");
ShlokHeader.push("VG[ lJGI[ SZLG[ I]ST V[JF H[ VDFZF");
ShlokHeader.push("VG[ U]~4 N[J VG[ ZFHF V[DG[ ;DL5[");
ShlokHeader.push("VG[ VDFZF VFlzT H[ ;J\" ;t;\\UL");
ShlokHeader.push("VDFZF H[ VFlzT HG T[D6[ 5MTFGF");
ShlokHeader.push("VG[ 36\\S K[ O/ H[G[ lJQF[ V[J]\\ 56 H[");
ShlokHeader.push("VG[ 5}J[\" YIF H[ DM8F 5]~QF T[D6[ 56");
ShlokHeader.push("VG[ SM.GL 56 H[ U]CI JFTF\" T[ TM SM.");
ShlokHeader.push("VG[ VDFZF H[ ;J[\" ;t;\\UL T[D6[");
ShlokHeader.push("VG[ T[ lJX[QF lGID T[ lSIF TM");
ShlokHeader.push("TYF EUJFGG[ ;FQ8F\\U GD:SFZ");
ShlokHeader.push("VG[ ;J\" H[ V[SFNXLVF[4 T[DG]\\ J|T");
ShlokHeader.push("VG[ H[ lNJ;[ J|TGM p5JF; SIM\" CMI");
ShlokHeader.push("VG[ ;J\" J{Q6JGF ZFHF V[JF H[ zL");
ShlokHeader.push("VG[ T[ Lj9=9,GFYHLV[ SIM\" H[ lG6\"I");
ShlokHeader.push("VG[ ;J[\" H[ VDFZF VFlzT4 T[D6[");
ShlokHeader.push("VG[ VDFZF H[ VFlzT T[D6[ lJQ6]");
ShlokHeader.push("VG[ HM SIFZ[S E}T5|[TFlNSGM p5N=J");
ShlokHeader.push("VG[ ;}I\"G]\\ G[ R\\N=DFG]\\ U|C6 YI[ ;T[");
ShlokHeader.push("VG[ T[ U|C6 D}SL ZCIF 5KL J:+");
ShlokHeader.push("VG[ VDFZF ;t;\\UL V[JF H[ RFZ[");
ShlokHeader.push("VG[ H[ A|FCD6 J6\" CMI4 T[D6[ XD");
ShlokHeader.push("VG[ J{xI J6\" CMI T[D6[ S\'lQFSD\"");
ShlokHeader.push("VG[ H[ lN=JH CMI4 T[D6[ UEF\"WFGFlNS");
ShlokHeader.push("VG[ SIFZ[S HF6[ VYJF VHF6[ HM");
ShlokHeader.push("VG[ RFZ J[N TYF jIF;;}+ TYF");
ShlokHeader.push("TYF zLEUJN=ULTF TYF lJN]ZHLV[");
ShlokHeader.push("VG[ WD\"XF:+GF DwIDF\\ ZCL V[JL H[");
ShlokHeader.push("VG[ 5MTFGF lCTG[ .rKTF V[JF H[");
ShlokHeader.push("VG[ T[ VF9 ;rKF:+DF\\YL VFRFZ4");
ShlokHeader.push("VG[ J/L V[ VF9 ;rKF:+G[ lJQF[ H[");
ShlokHeader.push("VG[ NXD:S\\W TYF 5\\RD:S\\W TYF");
ShlokHeader.push("VG[ zL ZFDFG]HFRFI[\" SI] V[J]\\ H[");
ShlokHeader.push("VG[ V[ ;J[\" ;rKF:+G[ lJQF[ H[ JRG T[ H[ T[");
ShlokHeader.push("T[ JRG H[ T[ ALHF JRG SZTF 5|WFG56[");
ShlokHeader.push("VG[ z]lT :D\'lT T[D6[ 5|lT5FNG SIM\" V[JM");
ShlokHeader.push("VG[ zLS\'Q6 EUJFG lJGF VgI 5NFY\"DF\\");
ShlokHeader.push("VG[ H[ HLJ K[ T[ CNIG[ lJQF[ ZCIM K[ G[");
ShlokHeader.push("VG[ H[ DFIF K[ T[ l+U]6FltDSF K[ G[");
ShlokHeader.push("VG[ H[ .`JZ K[4 T[ H[ T[ H[D CNIG[");
ShlokHeader.push("VG[ T[ .`JZ T[ SIF TM 5ZA|CD 5]~QFMtTD");
ShlokHeader.push("VG[ ;DY\" V[JF H[ zLS\'Q6 T[ H[ T[ ZFlWSFHLV[");
ShlokHeader.push("VG[ V[ zLS\'Q6 H[ T[ VH]\"G[ I]ST CMI tIFZ[");
ShlokHeader.push("VG[ V[ H[ ZFWFlNS EST T[ H[ T[ SIFZ[S");
ShlokHeader.push("V[ C[T] DF8[ V[ zLS\'Q6 EUJFGGF\\ H[ :J~5");
ShlokHeader.push("VG[ V[JF H[ T[ zLS\'Q6 EUJFG T[GL H[");
ShlokHeader.push("VG[ lJnFlNS U]6JF/F H[ 5]~QF4 T[DGF");
ShlokHeader.push("VG[ zLS\'Q6 EUJFG TYF zLS\'Q6");
ShlokHeader.push("VG[ :Y}/4 ;}1D VG[ SFZ6 v V[ H[");
ShlokHeader.push("VG[ zLDN=EFUJT 5]ZF6GM H[ NXD:S\\W");
ShlokHeader.push("VG[ V[ H[ NXD:S\\W T[G]\\ H[ 5]ZxRZ6 H[ T[");
ShlokHeader.push("VG[ SQ8GL N[GFZL V[JL SM. N[J ;\\A\\WL");
ShlokHeader.push("VG[ VFRFZ4 jIJCFZ VG[ 5|FIlxRT V[");
ShlokHeader.push("VG[ VDFZM H[ DT T[ lJlXQ8FN=J{T K[ V[D");
ShlokHeader.push("VG[ VF H[ 5}J[\" ;J[\" WD\" SCIF T[ H[ T[ ");
ShlokHeader.push("sCJ[ 5|YD WD\"J\\XL H[ VFRFI\" VG[");
ShlokHeader.push("VG[ T[ :+LVF[G[ SIFZ[I 56 V0J]\\");
ShlokHeader.push("VG[ jIJCFZ SFI\"G[ lJQF[ S[G]\\ 56 ");
ShlokHeader.push("VG[ 5MTFGF H[ lXQI4 T[D6[ WD\"");
ShlokHeader.push("VG[ EFNZJF ;]NL RT]YL\"G[ lNJ;[");
ShlokHeader.push("VG[ VDFZ[ VFlzT H[ ;J[\" ;t;\\UL4");
ShlokHeader.push("VG[ 5MTFGF VFlzT H[ ;J[\" ;t;\\UL");
ShlokHeader.push("VG[ DM8F H[ D\\lNZ T[DG[ lJQF[ VD[");
ShlokHeader.push("VG[ EUJFGGF\\ D\\lNZ 5|tI[ VFjIM");
ShlokHeader.push("VG[ lJnFYL\" E6FjIFGL XF/F SZFJLG[");
ShlokHeader.push("VG[ CJ[ V[ VIMwIF5|;FN VG[ Z3]JLZ");
ShlokHeader.push("VG[ J/L T[ A[ H6GL H[ 5tGLVF[ T[D6[");
ShlokHeader.push("sCJ[ U\'C:YFzDLGF H[ lJX[QF WD\" K[ T[");
ShlokHeader.push("VG[ T[ U\'C:YFzDL 5]~QF T[D6[ I]JFG");
ShlokHeader.push("VG[ H[ :+LG[ SM. 5|SFZGF jIJCFZ[");
ShlokHeader.push("VG[ U\'C:YFzDL T[D6[ 5MTFG[ 3[Z");
ShlokHeader.push("VG[ VDFZF VFlzT H[ U\'C:Y T[D6[");
ShlokHeader.push("VG[ J/L 5MTFGF J6F\"zDG[ 3l8T V[JM");
ShlokHeader.push("VG[ T[ U\'C:Y ;t;\\UL T[D6[ 5MTFGF");
ShlokHeader.push("VG[ UFI4 A/N4 E[\\;4 3M0F VFlNS H[");
ShlokHeader.push("VG[ ;F1FLV[ ;lCT ,BT SIF\" lJGF TM");
ShlokHeader.push("VG[ 5MTFG]\\ VYJF ALHFG]\\ H[ lJJFC");
ShlokHeader.push("VG[ 5MTFGL p5HG]\\ H[ N=jI T[G[ VG];FZ[");
ShlokHeader.push("VG[ 5MTFGF jIJCFZSFI\"G[ lJQF[ H[8,F");
ShlokHeader.push("VG[ T[ U\'C:YFzDL ;t;\\UL T[D6[ 5MTFGL");
ShlokHeader.push("VG[ V[SFNXL VFlNS H[ J|T T[DG]\\ H[");
ShlokHeader.push("VG[ zFJ6 DF;G[ lJQF[ zLDCFN[JG]\\ 5}HG4");
ShlokHeader.push("VG[ 5MTFGF H[ VFRFI\" T[ YSL TYF zLS\'Q6");
ShlokHeader.push("VG[ zLS\'Q6 EUJFG TYF 5MTFGF U]~");
ShlokHeader.push("VG[ 5MTFGF SFDSFH SZJF T[0IF H[ DH]Z");
ShlokHeader.push("VG[ H[ 9[SF6[ 5MT[ ZC[TF CM.V[ T[");
ShlokHeader.push("VG[ T[ HM 5MTFGF D}/ UZF;G]\\ TYF");
ShlokHeader.push("VG[ WGF-I V[JF H[ U\'C:Y ;t;\\UL");
ShlokHeader.push("VG[ WGF-I V[JF H[ U\'C:Y ;t;\\UL");
ShlokHeader.push("VG[ VDFZF VFlzT V[JF H[ ;t;\\UL");
ShlokHeader.push("VG[ T[ ZFHF T[D6[ ZFHIGF H[ ;FT V\\U");
ShlokHeader.push("sCJ[ ;]JFl;GL AF.VF[GF lJX[QF WD\" T[");
ShlokHeader.push("VG[ T[ ;]JFl;GL :+LVF[ T[D6[ ~5 VG[");
ShlokHeader.push("VG[ 5lTJ|TF V[JL H[ ;]JFl;GL :+LVF[");
ShlokHeader.push("VG[ ;]JFl;GL  :+LVF[ T[D6[ 5MTFGM");
ShlokHeader.push("sCJ[ lJWJF :+LVF[GF lJX[QF WD\" T[ SCLV[");
ShlokHeader.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF");
ShlokHeader.push("VG[ WFJ6M H[ AF/S T[GF :5X\"G[ lJQF[");
ShlokHeader.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF");
ShlokHeader.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF");
ShlokHeader.push("VG[ lJWJF :+LVF[ T[D6[ V[SJFZ");
ShlokHeader.push("VG[ T[ lJWJF :+LVF[ T[D6[ ;]JFl;GL");
ShlokHeader.push("VG[ UE\"GL 5F0GFZL H[ :+L T[GM");
ShlokHeader.push("VG[ I]JF VJ:YFG[ lJQF[ ZCL V[JL");
ShlokHeader.push("VG[ CM/LGL ZDT G SZJL4 VG[");
ShlokHeader.push("VG[ ;]JFl;GL G[ lJWJF V[JL H[ :+LVM");
ShlokHeader.push("VG[ J/L ZH:J,F V[JL H[ ;]JFl;GL");
ShlokHeader.push("CJ[ G{lQ9S A|CDRFZLGF H[ lJX[QF WD\"");
ShlokHeader.push("VG[ T[ :+LVF[GL JFTF\" SIFZ[I G SZJL");
ShlokHeader.push("VG[ N[JTFGL 5|lTDF lJGF ALHL H[ :+LGL");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL T[D6[ :+LGL");
ShlokHeader.push("VG[ :+LGF J[XG[ WZL ZCIM V[JM H[");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL4 T[D6[ 5MTFGF");
ShlokHeader.push("VG[ A/FtSFZ[ SZLG[ 5MTFG[ VlTXI");
ShlokHeader.push("VG[ HM SIFZ[S :+LVF[GM VYJF 5MTFGM");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL T[D6[ 5MTFG[");
ShlokHeader.push("VG[ H[ A|FCD6GF 3ZG[ lJQF[ :+L 5LZ;GFZL");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL4 T[D6[ J[NXF:+GM");
ShlokHeader.push("VG[ HFlTV[ SZLG[ H[ A|FCD6 CMI4 T[");
ShlokHeader.push("VG[ H[ A|FCD6 CMI T[G[ :GFG4 ;\\wIF");
ShlokHeader.push("CJ[ ;FW]GF H[ lJX[QF WD\" T[ SCLV[ KLV[");
ShlokHeader.push("VG[ ;J[\" H[ >lgN=IM T[ HLTJL G[ Z;GF");
ShlokHeader.push("VG[ SM.GL YF56 G ZFBJL VG[ SIFZ[I");
ShlokHeader.push("VG[ T[ ;FW] T[D6[4 VF5tSF/ 50IF");
ShlokHeader.push("VG[ H[ J:+ AC] D}&lt;IJF/]\\ CMI TYF");
ShlokHeader.push("VG[ lE1FF TYF ;EF 5|;\\U V[ A[ SFI\"");
ShlokHeader.push("VG[ H[ U\'C:YGF 3ZG[ lJQF[ ZF\\W[,");
ShlokHeader.push("T[JL ZLTG]\\ H[ U\'C:YG]\\ 3Z T[ 5|tI[");
ShlokHeader.push("VG[ 5}J[\" kQFEN[J EUJFGGF 5]+");
ShlokHeader.push("VG[ G{lQ9S A|CDRFZLG[ V[ ;FW] T[D6[");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL G[ ;FW] T[D6[ ");
ShlokHeader.push("VG[ ZMUFlNS VF5tSF/ 50IF lJGF");
ShlokHeader.push("VG[ T[ G{lQ9S A|CDRFZL G[ ;FW] T[D6[");
ShlokHeader.push("VG[ T[ ;FW] VG[ A|CDRFZL T[D6[ SM.S");
ShlokHeader.push("VG[ SM.G]\\ N}T56\\ G SZJ]\\ TYF RFl0IF56\\");
ShlokHeader.push("VG[ VDFZ[ VFlzT V[JF H[ ;t;\\UL AF.");
ShlokHeader.push("VG[ ;J[\" H[ ;rKF:+ T[GM H[ ;FZ T[G[ VD[");
ShlokHeader.push("V[ C[T] DF8[ VDFZF VFlzT H[ ;J[\"");
ShlokHeader.push("VG[ H[ VDFZF VFlzT 5]~QF G[ :+LVF[");
ShlokHeader.push("VG[ H[ AF.vEF.4 VF lX1FF5+L 5|DF6[");
ShlokHeader.push("VG[ VDFZF H[ VFlzT ;t;\\UL T[D6[");
ShlokHeader.push("VG[ VF lX1FF5+LG[ JF\\RL ;\\E/FJ[ V[JM");
ShlokHeader.push("VG[ VF H[ VDFZL lX1FF5+L K[ T[ H[ T[");
ShlokHeader.push(";\\JT !((Z V-FZ;M aIF;LGF DCF;]NL");
ShlokHeader.push("VG[ 5MTFGF VFlzT H[ ESTHG T[DGL");

var Shlok = ["zL ;CHFG\\N :JFDL H[ T[ 5MTFGF ;t;\\UL 5|tI[ lX1FF5+LG[ ,BTF YSF 5|YD 5MTFGF >Q8N[J4 H[ zLS\'Q6 EUJFG T[G]\\ wIFG~5 D\\U/FRZ6 SZ[ K[P<br /><br />C]\\ H[ T[ DFZF CNIG[ lJQF[ zLS\'Q6 EUJFGG]\\ wIFG S~\\ K]\\ T[ zLS\'Q6 S[JF K[4 TM H[GF 0FAF 50BFG[ lJQF[ ZFlWSFHL ZCIF K[4 VG[ H[GF J1Fo:Y/G[ lJQF[ ,1DLHL ZCIF K[ VG[ J\'\\NFJGG[ lJQF[ lJCFZGF SZGFZF K[P !"];
Shlok.push("VG[ J\'tTF,I UFDG[ lJQF[ ZCIF V[JF ;CHFG\\N :JFDL H[ VD[4 T[ VD[ H[ T[ GFGF 5|SFZGF H[ ;J[\" N[X T[DG[ lJQF[ ZCIF V[JF H[ VDFZF VFlzT ;J[\" ;t;\\UL T[ 5|tI[ lX1FF5+LG[ ,BLV[ KLV[P Z");
Shlok.push("zL WD\"N[J YSL K[ HgD H[DGM V[JF H[ VDFZF EF. ZFD5|TF5HL TYF .rKFZFDHL T[DGF 5]+ H[ VIMwIF5|;FN GFD[ VG[ Z3]JLZ GFD[ sH[G[ VD[ VDFZF NtT5]+ SZLG[ ;J[\" ;t;\\ULGF VFRFI\"56FG[ lJQF[ :YF5G SIF\" K[P #");
Shlok.push("TYF VDFZF VFlzT V[JF H[ D]S]\\NFG\\N VFlNS G{lQ9S A|CDRFZL TYF VDFZF VFlzT V[JF H[ DIFZFD E8=8 VFlNS U\'C:Y ;t;\\ULP $");
Shlok.push("TYF VDFZ[ VFlzT H[ ;]JFl;GL VG[ lJWJF V[JL ;J[\" AF.VF[ TYF D]STFG\\N VFlNS H[ ;J[\" ;FW]P 5");
Shlok.push("V[ ;J[\" T[D6[ 5MTFGF WD\"GL Z1FFGF SZGFZF VG[ XF:+G[ lJQF[ 5|DF6~5 VG[ zLDgGFZFI6GL :D\'lTV[ ;lCT V[JF H[ VDFZF ~0F VFXLJF\"N T[ JF\\RJFP &");
Shlok.push("VG[ VF lX1FF5+L ,bIFG]\\ H[ SFZ6 K[ T[ ;J[\" T[D6[ V[SFU| DG[ SZLG[ WFZJ]\\ VG[ VF lX1FF5+L H[ VD[ ,BL K[4 T[ ;J[\"GF HLJG[ lCTGL SZGFZL K[P *");
Shlok.push("VG[ zLDN= EFUJT 5]ZF6 VFlNS H[ ;tXF:+ T[D6[ HLJGF S&lt;IF6G[ VY[\" 5|lT5FNG SIF\" V[JF H[ VlC\\;F VFlNS ;NFRFZ T[DG[ H[ DG]QI 5F/[ K[ T[ DG]QI H[ T[ VF ,MSG[ 5Z,MSG[ lJQF[ DCF;]lBIF YFI K[P (");
Shlok.push("VG[ T[ ;NFRFZG]\\ p&LT;,\\3G SZLG[ H[ DG]QI 5MTFGF DGDF\\ VFJ[ T[D JT[\" K[4 T[ TM S]A]lwWJF/F K[ VG[ VF ,MS G[ 5Z,MSG[ lJQF[ lGxR[ DM8F SQ8G[ H 5FD[ K[P )");
Shlok.push("T[ DF8[ VDFZF lXQI V[JF H[ TD[ ;J[\" T[D6[ TM 5|LlTV[ SZLG[ VF lX1FF5+LG[ VG];ZLG[ H lGZ\\TZ ;FJWFG56[ JT\"J]\\4 56 lX1FF5+LG]\\ p&LT;,\\3G SZLG[ JT\"J]\\ GlCP !_");
Shlok.push("CJ[ T[ JtIF\"GL ZLT SCLV[ KLV[ H[ VDFZF H[ ;t;\\UL T[D6[ SM. HLJv5|F6LvDF+GL 56 :C\\;F G SZJL VG[ HF6LG[ TM hL6F V[JF H]4 DF\\S04 RF\\R0 VFlNS HLJ T[DGL 56 :C\\;F SIFZ[I G SZJLP !!");
Shlok.push("VG[ N[JTF VG[ l5T\' T[GF\\ I7G[ VY[\" 56 ASZF\\4 D\'U,F4 ;;,F4 DFK,F VFlNS SM. HLJGL lC\\;F G SZJL4 S[D H[ VlC\\;F K[ T[ H DM8M WD\" K[ V[D ;J\" XF:+DF\\ SCI]\\ K[P !Z");
Shlok.push("VG[ :+L4 WG VG[ ZFHI T[GL 5|Fl%TG[ VY[\" 56 SM. DG]QIGL lC\\;F TM SM. 5|SFZ[ SIFZ[I 56 G H SZJLP !#");
Shlok.push("VG[ VFtD3FT TM TLY\"G[ lJQF[ 56 G SZJM4 G[ S|MW[ SZLG[ G SZJM4 VG[ SIFZ[I SM. IMuI VFRZ6 Y> HFI T[ YSL D}\\hF.G[ 56 VFtD3FT G SZJM4 VG[ h[Z BF.G[ TYF U/[ 8]\\5M BF.G[ TYF S]J[ 50LG[ TYF 5J\"T p5ZYL 50LG[ .tIFlNS SM. ZLT[ VFtD3FT G SZJMP !$");
Shlok.push("VG[ H[ DF\\; K[ T[ TM I7G]\\ X[QF CMI TM 56 VF5tSF/DF\\ 56 SIFZ[I G BFJ]\\4 VG[ +6 5|SFZGL ;]ZF VG[ VlUIFZ 5|SFZG]\\ Dn T[ N[JTFG]\\ G{J[n CMI TM 56 G 5LJ]\\P !5");
Shlok.push("VG[ SIFZ[S 5MTFJT[ SF\\.S VIMuI VFRZ6 Y> UI]\\ CMI VYJF SM. ALHFJT[ VIMuI VFRZ6 Y> UI]\\ CMI TM X:+FlNS[ SZLG[ 5MTFGF V\\UG]\\ TYF ALHFGF V\\UG]\\ K[NG G SZJ]\\ VYJF S|MW[ SZLG[ 56 5MTFGF V\\UG]\\ TYF ALHFGF V\\UG]\\ K[NG G SZJ]\\P !&");
Shlok.push("VG[ WD\" SZJFG[ VY[\" 56 VDFZF ;t;\\UL SM.V[ RMZG]\\ SD\" G SZJ]\\ VG[ Wl6IFT]\\ H[ SFQ84 5]Q5 VFlNS J:T] T[ T[GF W6LGL VF7F lJGF G ,[J]\\P !*");
Shlok.push("VG[ VDFZF VFlzT H[ 5]~QF TYF :+LVF[ T[D6[ jIlERFZ G SZJM VG[ H]U8]\\ VFlNS H[ jI;G T[GM tIFU SZJMP VG[ EF\\uI4 DOZ4 DFHD4 UF\\HM VFlNS H[ S[O SZGFZF J:T] T[ BFJF\\ GlC VG[ 5LJF\\ 56 GlCP !(");
Shlok.push("VG[ H[GF CFYG]\\ ZF\\W[, VgG TYF H[GF 5F+G]\\ H/ T[ B5T]\\ G CMI T[6[ ZF\\W[, VgG TYF T[GF\\ 5F+G]\\ H/ T[ zLS\'Q6 EUJFGGL 5|;FNL RZ6FD\'TGF DFCFtdI[ SZLG[ 56 HUgGFY5]ZL lJGF VgI :YFGSG[ lJQF[ U|C6 G SZJ]\\ VG[ HUgGFY5]ZLG[ lJQF[ HUgGFYHLGM 5|;FN ,[JFI T[DF\\ NMQF GlC\\P !)");
Shlok.push("VG[ 5MTFGF :JFY\"GL l;lwWG[ VY[\" 56 SM.G[ lJQF[ lDyIF V5JFN VFZM56 G SZJM4 VG[ SM.G[ UF/ TM SIFZ[I G N[JLP Z_");
Shlok.push("VG[ N[JTF4 TLY\"4 A|FCD64 5lTJ|TF4 ;FW] VG[ J[N V[DGL lG\\NF SIFZ[I G SZJL VG[ G ;F\\E/JLP Z!");
Shlok.push("VG[ H[ N[JTFG[ ;]ZF VG[ DF\\;G]\\ G{J[n YT]\\ CMI VG[ J/L H[ N[JTFGL VFU/ ASZF VFlNS HLJGL lC\\;F YTL CMI T[ N[JTFG]\\ G{J[n G BFJ]\\P ZZ");
Shlok.push("VG[ DFU\"G[ lJQF[ RF,T[ lXJF,IFlNS H[ N[JD\\lNZ VFJ[ T[G[ HM>G[ T[G[ GD:SFZ SZJM VG[ VFNZ YSL T[ N[JG]\\ NX\"G SZJ]\\P Z#");
Shlok.push("VG[ 5MT5MTFGF J6F\"zDGM H[ WD\" T[ SM. ;t;\\ULV[ tIFU G SZJM4 VG[ 5ZWD\"G]\\ VFRZ6 G SZJ]\\ TYF 5FB\\0 WD\"G]\\ VFRZ6 G SZJ]\\ TYF SL&lt;5T WD\"G]\\ VFRZ6 G SZJ]\\P Z$");
Shlok.push("VG[ H[GF JRGG[ ;F\\E/J[ SZLG[ zLS\'Q6 EUJFGGL ELST G[ 5MTFGM WD\" V[ A[ YSL 50L HJFI T[GF\\ D]BYSL EUJFGGL SYF JFTF\" G ;F\\E/JLP Z5");
Shlok.push("VG[ H[ ;tI JRG AM,J[ SZLG[ 5MTFGM N|MC YFI TYF 5FZSM N|MC YFI V[J]\\ H[ ;tI JRG T[ SIFZ[I G AM,J]\\4 VG[ H[ S\'T3=GL CMI T[GF\\ ;\\UGM tIFU SZJM4 VG[ jIJCFZSFI\"G[ lJQF[ SM.GL ,F\\R G ,[JLP Z&");
Shlok.push("VG[ RMZ4 5F5L4 jI;GL4 5FB\\0L4 SFDL TYF SLlDIF VFlNS lSIFV[ SZLG[ HGGM 9UGFZM V[ K 5|SFZGF H[ DG]QI T[DGM ;\\U G SZJMPZ* ");
Shlok.push("VG[ H[ DG]QI ElSTG]\\ VYJF 7FGG]\\ VF,\\AG SZLG[ :+L4 N|jI VG[ Z;F:JFN T[G[ lJQF[ VlTXI ,M,]5YSF 5F5G[ lJQF[ 5|JT\"TF CMI T[ DG]QIGM ;DFUD G SZJMP Z(");
Shlok.push("VG[ H[ XF:+G[ lJQF[ zLS\'Q6 EUJFG TYF zLS\'Q6 EUJFGGF H[ JZFCFlNS VJTFZ T[DG]\\ I]lSTV[ SZLG[ B\\0G SI]\\ CMI4 V[JF\\ H[ XF:+ T[ SIFZ[I G DFGJF VG[ G ;F\\E/JFP Z)");
Shlok.push("VG[ UF?IF lJGFG]\\ H[ H/ TYF N}W T[ G 5LJ]\\4 VG[ H[ H/G[ lJQF[ hL6F HLJ 36F\\S CMI T[ H/[ SZLG[ :GFGFlNS lS|IF G SZJLP#_ ");
Shlok.push("VG[ H[ VF{QFW NF~ TYF DF\\; T[6[ I]ST CMI T[ VF{QFW SIFZ[I G BFJ]\\ VG[ J/L H[ J{nGF VFRZ6G[ HF6TF G CM.V[ T[ J{n[ VF%I]\\ H[ VF{QFW T[ 56 SIFZ[I G BFJ]\\P#! ");
Shlok.push("VG[ ,MS G[ XF:+ T[D6[ D/D}+ SZJFG[ VY[\" JHIF\" V[JF H[ :YFGS H[ HL6\" N[JF,I TYF GNL T/FJGF VFZF TYF DFU\" TYF JFJ[,]\\ B[TZ4 J\'1FGL KFIF TYF O},JF0L AULRF V[ VFlNS H[ :YFGS T[G[ lJQF[ D/D}+ G SZJ]\\ TYF Y]\\SJ]\\ 56 GlC\\P #Z");
Shlok.push("VG[ RMZ DFU[\" SZLG[ 5[;J]\\ GlC VG[ lG;ZJ]\\ GlC4 VG[ H[ :YFGS Wl6IFT]\\ CMI T[ :YFGSG[ lJQF[ T[GF\\ W6LG[ 5}KIF lJGF pTFZM G SZJMP ##");
Shlok.push("VG[ VDFZF ;t;\\UL H[ 5]~QF DF+ T[D6[ AF. DF6;GF D]B YSL 7FGJFTF\" G ;F\\E/JL4 VG[ :+LVF[ ;FY[ lJJFN G SZJM TYF ZFHF ;\\UFY[ TYF ZFHFGF DF6; ;\\UFY[ lJJFN G SZJMP #$");
Shlok.push("VG[ U]~G]\\ V5DFG G SZJ]\\ TYF H[ VlTXI z[Q9 DG]QI CMI TYF H[ ,MSG[ lJQF[ 5|lTlQ9T DG]QI CMI TYF H[ lJN=FG DG]QI CMI TYF H[ X:+WFZL DG]QI CMI T[ ;J[\"G]\\ V5DFG G SZJ]\\P #5");
Shlok.push("VG[ lJRFIF\" lJGF TtSF/ SM. SFI\" G SZJ]\\4 VG[ WD\" ;\\A\\WL H[ SFI\" T[ TM TtSF/ SZJ]\\4 VG[ 5MT[ H[ lJnF E^IF CM.V[ T[ ALHFG[ E6FJJL4 VG[ lGtI 5|tI[ ;FW]GM ;DFUD SZJMP #&");
Shlok.push("VG[ U]~4 N[J VG[ ZFHF V[ +6GF NX\"GG[ VY[\" HIFZ[ HJ]\\ tIFZ[ 9F,[ CFY[ G HJ]\\4 VG[ SM.GM lJ`JF;3FT G SZJM4 VG[ 5MTFGF D]B[ SZLG[ 5MTFGF\\ JBF6 G SZJFP #*");
Shlok.push("VG[ H[ J:+ 5C[I[\" YS[ 5MTFGF\\ V\\U N[BFI T[J]\\ H[ E}\\0]\\ J:+ T[ VDFZF ;t;\\UL T[D6[ G 5C[ZJ]\\P #(");
Shlok.push("VG[ zLS\'Q6 EUJFGGL H[ ElST T[ WD[\"ZlCT V[JL SM. 5|SFZ[ G SZJL VG[ V7FGL V[JF H[ DG]QI T[DGL lG\\NFGF EI YSL zLS\'Q6 EUJFGGL ;[JFGM tIFU SZJM H GlCP #)");
Shlok.push("VG[ pt;JGF lNJ;G[ lJQF[ TYF lGtI 5|tI[ zLS\'Q6GF D\\lNZDF\\ VFjIF V[JF H[ ;t;\\UL 5]~QF T[D6[ T[ D\\lNZG[ lJQF[ :+LVF[GM :5X\" G SZJM4 TYF :+LVF[ T[D6[ 5]~QFGM :5X\" G SZJM4 VG[ D\\lNZDF\\YL GL;IF\" 5KL 5MT5MTFGL ZLT[ JT\"J]\\P $_");
Shlok.push("VG[ WD\"J\\XL U]~ YSL zLS\'Q6 EUJFGGL NL1FFG[ 5FdIF V[JF H[ A|FCD64 1Fl+I VG[ J{xI V[ +6 J6\"GF VDFZF ;t;\\UL T[D6[ S\\9G[ lJQF[ T],;LGL A[J0L DF/F lGtI WFZJL4 VG[ ,,F84 CNI VG[ A[ CFY V[ RFZ[ 9[SF6[ pwJ\"5]\\0= lT,S SZJ]\\P $!");
Shlok.push("VG[ T[ lT,S H[ T[ UM5LR\\NG[ SZLG[ SZJ]\\4 VYJF EUJFGGL 5}HF SZTF\\ AFSL ZCIF]\\ VG[ S[;Z S]\\S]DFlNS[ I]ST V[J]\\ H[ 5|;FNL R\\NG T[6[ SZLG[ lT,S SZJ]\\P $Z");
Shlok.push("VG[ T[ lT,SGF DwIG[ lJQF[ H UM/ V[JM H[ RF\\N,M T[ H[ T[ UM5LR\\NG[ SZLG[ SZJM4 VYJF ZFlWSFHL VG[ ,1DLHL T[G]\\ 5|;FNL V[J]\\ H[ S]\\S]D T[6[ SZLG[ T[ RF\\N,M SZJMP $#");
Shlok.push("VG[ 5MTFGF WD\"G[ lJQF[ ZCIF VG[ zLS\'Q6GF EST V[JF H[ ;rK]N| T[D6[ TM T],;LGL DF/F VG[ pwJ\"5]\\0= lT,S T[ A|FCD64 1Fl+I4 J{xIGL 5[9[ WFZJFP $$");
Shlok.push("VG[ T[ ;rK]N| YSL ALHF H[ HFlTV[ SZLG[ pTZTF V[JF ESTHG T[D6[ TM R\\NGFlNS SFQ8GL H[ A[J0L DF/F T[ EUJFGGL 5|;FNL SZFJLG[ S\\9G[ lJQF[ WFZJL4 VG[ ,,F8G[ lJQF[ S[J/ RF\\N,M SZJM 56 lT,S G SZJ]\\P $5");
Shlok.push("VG[ H[ A|FCD6FlNSG[ l+5]\\0= H[ VF0]\\ lT,S SZJ]\\ TYF ~N|F1FGL DF/F WFZJL V[ A[ JFGF 5MTFGL S]/ 5Z\\5ZFV[ SZLG[ RF&lt;IF VFjIF\\ CMI VG[ T[ A|FCD6FlNS VDFZF VFlzT YIF CMI4 TM 56 T[D6[ l+5]\\0= VG[ ~N|F1FGM SIFZ[I tIFU G SZJMP $&");
Shlok.push("VG[ GFZFI6 VG[ lXJHL V[ A[IG]\\ V[SFtD56\\ H HF6J]\\4 S[D H[ J[NG[ lJQF[ V[ A[IG]\\ A|CD~5[ SZLG[ 5|lT5FNG SI]\\ K[P $*");
Shlok.push("VG[ VDFZF VFlzT H[ DG]QI T[D6[ XF:+[ SCIM H[ VF5N=WD\" T[ V&lt;5 VF5tSF/G[ lJQF[ D]bI56[ SZLG[ SIFZ[I U|C6 G SZJMP $(");
Shlok.push("VG[ VDFZF ;t;\\UL T[D6[ lGtI ;}I\" puIFYL 5|YD H HFUJ]\\4 VG[ zLS\'Q6 EUJFGG]\\ :DZ6 SZLG[ 5KL XF{RlJlW SZJF HJ]\\P $)");
Shlok.push("VG[ 5KL V[S :YFGSG[ lJQF[ A[;LG[ NFT6 SZJ]\\ VG[ 5KL 5lJ+ H/[ SZLG[ :GFG SZLG[ 5KL WMI[,]\\ J:+ V[S 5C[ZJ]\\ VG[ V[S VF[-J]\\P 5_");
Shlok.push("VG[ T[ JFZ 5KL 5lJ+ 5\'yJLG[ lJQF[ 5FYI]\\ VG[ X]wW G[ SM. ALHF VF;GG[ V0I]\\ G CMI VG[ H[ p5Z ;FZL 5[9[ A[;FI V[J]\\ H[ VF;G T[G[ lJQF[ 5]J\"D]B[ VYJF ptTZD]B[ A[;LG[ VFRDG SZJ]\\P5!");
Shlok.push("VG[ 5KL ;t;\\UL 5]~QFDF+G[ RF\\N,[ ;lCT pwJ\"5]\\0= lT,S SZJ]\\ VG[ ;]JFl;GL H[ :+LVF[ T[D6[ TM 5MTFGF EF,G[ lJQF[ S]\\S]DGM RF\\N,M SZJMP 5Z");
Shlok.push("VG[ T[ lJWJF :+LVF[ DF+G[ 5MTFGF EF,G[lJQF[ lT,S G SZJ]\\ G[ RF\\N,M 56 G SZJM VG[ T[ 5KL T[ ;J[\" H[ VDFZF ;t;\\UL T[D6[ DG[ SZLG[ S&lt;%IF H[ R\\NG 5]Q5FlNS p5RFZ T[D6[ SZLG[ zLS\'Q6 EUJFGGL DFG;L 5}HF SZJLP 5#");
Shlok.push("VG[ T[ 5KL zLZFWFS\'Q6GL H[ lR+ 5|lTDF T[G]\\ VFNZYSL NX\"G SZLG[ GD:SFZ SZLG[ 5KL 5MTFGF ;FDyI\" 5|DF6[ zLS\'Q6GM VQ8F1FZ D\\+ T[GM H5 SZLG[ T[ 5KL 5MTFG]\\ jIJCFlZS SFDSFH SZJ]\\P 5$");
Shlok.push("VG[ H[ VDFZF ;t;\\ULDF\\ V\\AZLQF ZFHFGL 5[9[ VFtDlGJ[NL V[JF ptTD EST CMI T[D6[ 56 5|YD SCIF]\\ T[JL ZLT[ VG]S|D[ SZLG[ DFG;L 5}HF 5I\"\\T ;J[\" Ls|IF SZJLP 55");
Shlok.push("VG[ T[ H[ VFtDlGJ[NL EST T[D6[ 5FQFF6GL VYJF WFT]GL H[ zLS\'Q6 EUJFGGL 5|lTDF VYJF XF,U|FD T[GL H[ 5}HF T[ N[XSF/G[ VG];ZLG[ 5MTFGF ;FDyI\" 5|DF6[ 5|F%T YIF H[ R\\NG 5]Q5 O,FlNS J:T] T[6[ SZLG[ SZJL VG[ 5KL zLS\'Q6 EUJFGGM H[ VQ8F1FZ D\\+ T[GM H5 SZJMP 5&");
Shlok.push("VG[ T[ 5KL zLS\'Q6 EUJFGGF H[ :TM+ VYJF U|\\Y T[GM H[ 5F9 T[ 5MTFGF ;FDyI\" 5|DF6[ SZJM VG[ H[ ;\\:S\'T G E^IF CMI T[D6[ zLS\'Q6 EUJFGG]\\ GFDSLT\"G SZJ]\\P 5*");
Shlok.push("VG[ 5KL zLS\'Q6 EUJFGG[ G{J[n SZLG[ 5KL T[ 5|;FNL V[J]\\ H[ VgG T[ HDJ]\\ VG[ T[ H[ VFtDlGJ[NL J{Q6J T[D6[ ;J\"SF/G[ lJQF[ 5|LlTV[ SZLG[ zLS\'Q6 EUJFGGL ;[JF5ZFI6 YJ]\\P 5(");
Shlok.push("VG[ lGU]\"6 SC[TF DFIFGF H[ ;tJFlNS +6 U]6 T[6[ ZlCT V[JF H[ zLS\'Q6 EUJFG T[GF\\ ;\\A\\WYSL T[ VFtDlGJ[NL ESTGL H[ ;J[\" Ls|IF T[ lGU]\"6 YFI K[ T[ C[T] DF8[ T[ VFtDlGJ[NL EST H[ T[ lGU]\"6 SCIF K[P 5)");
Shlok.push("VG[ V[ H[ VFtDlGJ[NL EST T[D6[ zLS\'Q6 EUJFGG[ V5\"6 SIF\" lJGFG]\\ H/56 SIFZ[I G 5LJ]\\ VG[ 5+ S\\N O,FlNS H[ J:T] T[ 56 zLS\'Q6 EUJFGG[ V5\"6 SIF\" lJGFG]\\ G BFJ]\\P &_");
Shlok.push("VG[ J/L ;J[\" H[ VDFZF ;t;\\UL T[D6[ J\'wWF56FYSL VYJF SM. DM8F VF5tSF,[ SZLG[ V;DY\"56\\ Y> UI[ ;T[ 5MT[ ;[JJFG]\\ H[ zLS\'Q6G]\\ :J~5 T[ ALHF ESTG[ VF5LG[ 5MT[ 5MTFGF ;FDyI\" 5|DF6[ JT\"J]\\P &!");
Shlok.push("VG[ H[ zLS\'Q6G]\\ :J~5 5MTFG[ ;[JJFG[ VY[\" WD\"J\\XGF H[ VFRFI\" T[D6[ H VF%I]\\ CMI VYJF T[ VFRFI[\" H[ :J~5GL 5|lTQ9F SZL CMI T[ H :J~5G[ ;[JJ]\\ VG[ T[ lJGF ALH]\\ H[ zLS\'Q6G]\\ :J~54 T[ TM GD:SFZ SZJF IMuI K[ 56 ;[JJF IMuI GYLP &Z");
Shlok.push("VG[ VDFZF H[ ;J[\" ;t;\\UL T[D6[ lGtI 5|tI[ ;FI\\SF/[ EUJFGGF D\\lNZ 5|tI[ HJ]\\ VG[ T[ D\\lNZG[ lJQF[ zLZFlWSFHLGF 5lT V[JF H[ zLS\'Q6 EUJFG T[GF\\ GFDG]\\ prR :JZ[ SZLG[ lST\"G SZJ]\\P &#");
Shlok.push("VG[ T[ zLS\'Q6GL H[ SYFJFTF\" T[ 5ZD VFNZYSL SZJL VG[ ;F\\E/JL VG[ pt;JG[ lNJ;[ JFlH+ ;lCT zLS\'Q6GF lST\"G SZJFP &$");
Shlok.push("VG[ VDFZF VFlzT H[ ;J[\" ;t;\\UL T[D6[ H[ 5|SFZ[ 5}J[\" SCI]\\ V[ 5|SFZ[ SZLG[ H lGtI 5|tI[ SZJ]\\ VG[ ;\\:S\'T VG[ 5|FS\'T V[JF H[ ;NU|\\Y T[DGM VeIF; 56 5MTFGL A]lwWG[ VG];FZ[ SZJMP &5");
Shlok.push("VG[ H[ DG]QI H[JF U]6[ SZLG[ I]ST CMI T[ DG]QIG[ T[JF SFI\"G[lJQF[ lJRFZLG[ H 5|[ZJM 56 H[ SFI\"G[lJQF[ H[ IMuI G CMI T[ SFI\"G[ lJQF[ T[G[ SIFZ[I G 5|[ZJMP &&");
Shlok.push("VG[ 5MTFGF H[ ;[JS CMI4 T[ ;J\"GL 5MTFGF ;FDyI\" 5|DF6[ VgGJ:+FlNS[ SZLG[ IYFIMuI ;\\EFJGF lGZ\\TZ ZFBJLP &*");
Shlok.push("VG[ H[ 5]~QF H[JF U]6JF/M CMI T[ 5]~QFG[ T[JF JRG[ SZLG[ N[X SF/FG];FZ[ IYFIMuI AM,FJJM 56 V[YL ALHL ZLT[ G AM,FJJMP &(");
Shlok.push("VG[ lJGI[ SZLG[ I]ST V[JF H[ VDFZF VFlzT ;t;\\UL T[D6[ U]~4 ZFHF4 VlTJ\'wW4 tIFUL4 lJN=jFG VG[ T5:JL V[ K H6F VFJ[ tIFZ[ ;gD]B p9J]\\ TYF VF;G VF5J]\\ TYF DW]Z[ JRG[ AM,FJJ]\\ .tIFlNS ls|IFV[ SZLG[ V[DG]\\ ;gDFG SZJ]\\P &)");
Shlok.push("VG[ U]~4 N[J VG[ ZFHF V[DG[ ;DL5[ TYF ;EFG[ lJQF[ 5U p5Z 5U R-FJLG[ G A[;J]\\ TYF J:+[ SZLG[ 0l\\R6G[ AF\\WLG[ G A[;J]\\P *_");
Shlok.push("VG[ VDFZF VFlzT H[ ;J\" ;t;\\UL T[D6[ 5MTFGF VFRFI\" ;\\UFY[ SIFZ[I 56 lJJFN G SZJM VG[ 5MTFGF ;FDyI\" 5|DF6[ VgG4 WG4 J:+FlNS[ SZLG[ T[ 5MTFGF VFRFI\"G[ 5}HJFP *!");
Shlok.push("VDFZF H[ VFlzT HG T[D6[ 5MTFGF VFRFI\"G[ VFJTF ;F\\E/LG[ VFNZ YSL TtSF/ ;gD]B HJ]\\ VG[ T[ VFRFI\" 5MTFGF UFDYL 5FKF 5WFZ[ tIFZ[ UFDGL EFUM/ ;]WL J/FJJF HJ]\\P *Z");
Shlok.push("VG[ 36\\S K[ O/ H[G[ lJQF[ V[J]\\ 56 H[ SD\"4 T[ HM WD[\" ZlCT CMI TM T[G]\\ VFRZ6 G H SZJ]\\ S[D H[ WD\" K[ T[ H ;J\" 5]~QFFY\"GM VF5GFZM K[ DF8[ SM.S O/GF ,ME[ SZLG[ WD\"GM tIFU G SZJMP *#");
Shlok.push("VG[ 5}J[\" YIF H[ DM8F 5]~QF T[D6[ 56 HM SIFZ[I VWDF\"RZ6 SI]\\ CMI TM T[G]\\ U|C6 G SZJ]\\ VG[ T[D6[ H[ WDF\"RZ6 SI]\\ CMI TM T[G]\\ U|C6 SZJ]\\P *$");
Shlok.push("VG[ SM.GL 56 H[ U]CI JFTF\" T[ TM SM. 9[SF6[ 56 5|SFX SZJL H GlC VG[ H[ HLJG]\\ H[JL ZLT[ ;gDFG SZJ]\\ 38T]\\ CMI4 T[G]\\ T[JL ZLT[ H ;gDFG SZJ]\\ 56 ;DN|lQ8V[ SZLG[ V[ DIF\"NFG]\\ p&LT;,\\3G SZJ]\\ GlCP *5");
Shlok.push("VG[ VDFZF H[ ;J[\" ;t;\\UL T[D6[ RFT]DF\";G[ lJQF[ lJX[QF lGID WFZJM4 VG[ H[ DG]QI V;DY\" CMI T[D6[ TM V[S zFJ6 DF;G[ lJQF[ lJX[QF lGID WFZJMP *&");
Shlok.push("VG[ T[ lJX[QF lGID T[ lSIF TM EUJFGGL SYFG]\\ zJ6 SZJ]\\ TYF SYF JF\\RJL TYF EUJFGGF U]6G]\\ lST\"G SZJ]\\ TYF 5\\RFD\'T :GFG[ SZLG[ EUJFGGL DCF5}HF SZJL TYF EUJFGGF D\\+GM H5 SZJM TYF :TM+GM 5F9 SZJM TYF EUJFGG[ 5|Nl1F6FVM SZJLP **");
Shlok.push("TYF EUJFGG[ ;FQ8F\\U GD:SFZ SZJF V[ H[ VF9 5|SFZGF lGID T[ VD[ ptTD DFgIF K[P T[ DF8[ V[ lGIDDF\\YL SM. V[S lGID H[ T[ RMDF;FG[ lJQF[ lJX[QF56[ ElSTV[ SZLG[ WFZJMP *(");
Shlok.push("VG[ ;J\" H[ V[SFNXLVF[4 T[DG]\\ J|T H[ T[ VFNZYSL SZJ]\\ TYF zLS\'Q6 EUJFGGF H[ HgDFQ8DL VFlNS HgDlNJ; T[DG]\\ J|T H[ T[ VFNZYSL SZJ]\\ TYF lXJZF+LG]\\ J|T H[ T[ VFNZYSL SZJ]\\ VG[ T[ J|TGF lNJ;G[ lJQF[ DM8F\\ pt;J SZJFP *)");
Shlok.push("VG[ H[ lNJ;[ J|TGM p5JF; SIM\" CMI T[ lNJ;[ VlTXI ItG[ SZLG[ lNJ;GL lGN|FGM tIFU SZJM4 S[D H[ H[D D{Y]G[ SZLG[ DG]QIGF p5JF;GM GFX YFI K[ T[D H lNJ;GL lGN|FV[ SZLG[ DG]QIGF p5JF;GM GFX Y> HFI K[P (_");
Shlok.push("VG[ ;J\" J{Q6JGF ZFHF V[JF H[ zL J&LT;,EFRFI\" T[GF\\ 5]+ H[ zL lJ9=9,GFYHL T[ H[T[ J|T VG[ pt;JGF lG6\"IG[ SZTF CJFP (!");
Shlok.push("VG[ T[ lJ9=9,GFYHLV[ SIM\" H[ lG6\"I T[G[ H VG];ZLG[ ;J[\" J|T G[ pt;J SZJF4 VG[ T[ lJ9=9,GFYHLV[ SCL H[ zLS\'Q6GL ;[JF ZLTL T[G]\\ H U|C6 SZJ]\\P (Z");
Shlok.push("VG[ ;J[\" H[ VDFZF VFlzT4 T[D6[ N=JFlZSF VFlNS H[ TLY\" T[DGL IF+F H[ T[ 5MTFGF ;FDyI\" 5|DF6[ IYFlJlWV[ SZLG[ SZJL VG[ J/L 5MTFGF ;FDyI\" 5|DF6[ NLGHGG[ lJQF[ NIFJFG YJ]\\P (#");
Shlok.push("VG[ VDFZF H[ VFlzT T[D6[ lJQ64 lXJ4 U65lT4 5FJ\"TL VG[ ;}I\" V[ 5F\\R N[J 5}HI 56[ SZLG[ DFGJFP ($");
Shlok.push("VG[ HM SIFZ[S E}T5|[TFlNSGM p5N|J YFI tIFZ[ TM GFZFI6 SJRGM H5 SZJM VYJF CG]DFGHLGF D\\+GM H5 SZJM4 56 V[ lJGF ALHF SM. X]N| N[JGF :TM+ VG[ D\\+GM H5 G SZJMP (5");
Shlok.push("VG[ ;}I\"G]\\ G[ R\\N|DFG]\\ U|C6 YI[ ;T[ VDFZF H[ ;J[\" ;t;\\UL T[D6[ ALHL ;J[\" lS|IFGM TtSF/ tIFU SZLG[ 5lJ+ Y.G[ zLS\'Q6 EUJFGGF D\\+GM H5 SZJMP (&");
Shlok.push("VG[ T[ U|C6 D}SL ZCIF 5KL J:+ ;lCT :GFG SZLG[ H[ VDFZF U\'C:Y ;t;\\UL CMI4 T[D6[ 5MTFGF ;FDyI\" 5|DF6[ NFG SZJ]\\ VG[ H[ tIFUL CMI T[D6[ EUJFGGL 5}HF SZJLP (*");
Shlok.push("VG[ VDFZF ;t;\\UL V[JF H[ RFZ[ J6\"GF DG]QI4 T[D6[ HgDG]\\ ;}TS TYF DZ6G]\\ ;}TS T[ 5MT5MTFGF ;\\A\\WG[ VG];FZ[ SZLG[ IYFXF:+ 5F/J]\\P ((");
Shlok.push("VG[ H[ A|FCD6 J6\" CMI4 T[D6[ XD4 ND4 1FDF VG[ ;\\TMQF V[ VFlNS H[ U]6 T[D6[ I]ST YJ]\\ VG[ H[ 1Fl+I J6\" CMI T[D6[ X]ZJLZ56\\ VG WLZH V[ VFlNS H[ U]6 T[D6[ I]ST YJ]\\P ()");
Shlok.push("VG[ J{xI J6\" CMI T[D6[ S\'lQFSD\" TYF J6H jIF5FZ TYF jIFHJ8M V[ VFlNS[ H[ J\'ltTVF[ T[D6[ SZLG[ JT\"J]\\ VG[ H[ X]N| J6\" CMI4 T[D6[ A|FCD6FlNS +6 J6\"GL ;[JF SZJL V[ VFlNS H[ J\'ltTVF[ T[D6[ SZLG[ JT\"J]\\P )_");
Shlok.push("VG[ H[ lN=H CMI4 T[D6[ UEF\"WFGFlNS ;\\:SFZ TYF VFlC=GS TYF zFwW V[ +6 H[ T[ 5MTFGF U\'CI;}+G[ VG];FZ[4 H[JM H[GM VJ;Z CMI VG[ H[JL WG;\\5ltT CMI T[ 5|DF6[ SZJFP )!");
Shlok.push("VG[ SIFZ[S HF6[ VYJF VHF6[ HM GFG]\\ DM8]\\ 5F5 Y. HFI TM 5MTFGL XlST 5|DF6[ T[ 5F5G]\\ 5|FIlxRT SZJ]\\P )Z");
Shlok.push("VG[ RFZ J[N TYF jIF;;}+ TYF zLDN=EFUJT GFD[ 5]ZF6 TYF DCFEFZTG[ lJQF[ TM zL lJQ6];C:+GFDP )#");
Shlok.push("TYF zLEUJN=ULTF TYF lJN]ZHLV[ SC[,L H[ GLlT TYF :S\\N5]ZF6GM H[ lJQ6]B\\0 T[G[ lJQF[ ZCI]\\ V[J]\\ H[ zLJF;]N[JDFCFtdIP )$");
Shlok.push("VG[ WD\"XF:+GF DwIDF\\ ZCL V[JL H[ IF7J&lt;SI klQFGL :D\'lT V[ H[ VF9 ;rKF:+ T[ VDG[ .Q8 K[P )5");
Shlok.push("VG[ 5MTFGF lCTG[ .rKTF V[JF H[ VDFZF ;J[\" lXQI T[D6[ V[ VF9 ;rKF:+ H[ T[ ;F\\E/JF4 VG[ VDFZF VFlzT H[ lN=jH T[D6[ V[ ;rKF:+ H[ T[ E6JF TYF E6FJJF TYF V[DGL SYF SZJLP )&");
Shlok.push("VG[ T[ VF9 ;rKF:+DF\\YL VFRFZ4 jIJCFZ VG[ 5|FIlxRT V[ +6GM H[ lG6\"I SZJM T[G[ lJQF[ TM lDTF1FZF 8LSFV[ I]ST V[JL H[ IF7J&lt;SI klQFGL :D\'lT4 T[G]\\ U|C6 SZJ]\\P )*");
Shlok.push("VG[ J/L V[ VF9 ;rKF:+G[ lJQF[ H[ zLDN=EFUJT 5]ZF6 T[GF\\ NXD G[ 5\\RD GFD[ H[ A[ :S\\W4 T[ H[ T[ zLS\'Q6 EUJFGG]\\ DFCFtdI HF6JFG[ VY[\" ;J\"YL VlWS56[ HF6JFP )(");
Shlok.push("VG[ NXD:S\\W TYF 5\\RD:S\\W TYF IF7J&lt;SIGL :D\'lT V[ H[ +6 T[ VG]S|D[ SZLG[ VDF~\\ ElSTXF:+4 IMUXF:+ VG[ WD\"XF:+ K[P SC[TF NXD:S\\W T[ ElSTXF:+ K[ VG[ 5\\RD:S\\W T[ IMUXF:+ K[ VG[ IF7J&lt;SIGL :D\'lT T[ VwIFtDXF:+ K[ V[D HF6J]\\P ))");
Shlok.push("VG[ zL ZFDFG]HFRFI[\" SI]\\ V[J]\\ H[ jIF;;]+G]\\ zLEFQI TYF zLEUJN=ULTFG]\\ EFQI V[ H[ A[ T[ VDF~\\ VwIFtDXF:+ K[ V[D HF6J]\\P !__");
Shlok.push("VG[ V[ ;J[\" ;rKF:+G[ lJQF[ H[ JRG T[ H[ T[ zLS\'Q6 EUJFGG]\\ :J~5 TYF WD\" TYF ElST TYF J{ZFuI V[ RFZGF VlT ptSQF\"56FG[ SC[TF CMIP  !_!");
Shlok.push("T[ JRG H[ T[ ALHF JRG SZTF 5|WFG56[ DFGJF VG[ zLS\'Q6 EUJFGGL ElST H[ T[ WD[\" ;lCT H SZJL4 V[JL ZLT[ T[ ;J[\" ;rKF:+G]\\ ZC:I K[P !_Z");
Shlok.push("VG[ z]lT :D\'lT T[D6[ 5|lT5FNG SIM\" V[JM H[ ;NFRFZ4 T[ WD\" HF6JM4 VG[ zLS\'Q6 EUJFGG[ lJQF[ DFCFtdI7FG[ ;lCT H[ 36M :G[C T[ ElST HF6JLP !_#");
Shlok.push("VG[ zLS\'Q6 EUJFG lJGF VgI 5NFY\"DF\\ 5|LlT GlC T[ J{ZFuI HF6JMP VG[ HLJ4 DFIF VG[ .`JZ T[DGF :J~5G[ H[ ~0L ZLT[ HF6J]\\ T[G[ 7FG SCLV[P !_$");
Shlok.push("VG[ H[ HLJ K[ T[ CNIG[ lJQF[ ZCIFM K[ G[ V6] ;ZBM ;}1D K[ G[ R{TgI~5 K[ G[ HF6GFZM K[4 VG[ 5MTFGL 7FGXlSTV[ SZLG[ GBYL lXBF5I\"\\T ;DU| 5MTFGF N[C 5|tI[ jIF5LG[ ZCIFM K[4 VG[ VK[n4 VE[n4 VHZ4 VDZ .tIFlNS K[ ,1F6 H[GF\\ V[JM HLJ K[ V[D HF6J]\\P !_5××");
Shlok.push("VG[ H[ DFIF K[ T[ l+U]6FltDSF K[ G[ V\\WSFZ ~5 K[ G[ zLS\'Q6 EUJFGGL XlST K[4 VG[ VF HLJG[ N[C TYF N[CGF H[ ;\\A\\WL T[D6[ lJQF[ VC\\DDtJGL SZFJGFZL K[4 V[D DFIFG[ HF6JLP !_&");
Shlok.push("VG[ H[ .`JZ K[4 T[ H[ T[ H[D CNIG[ lJQF[ HLJ ZCIM K[4 T[D T[ HLJG[ lJQF[ V\\TIF\"DL56[ SZLG[ ZCIF K[P G[ :JT\\+ K[ G[ ;J\" HLJG[ SD\"O/GF VF5GFZF K[4 V[D .`JZG[ HF6JFP !_*");
Shlok.push("VG[ T[ .`JZ T[ SIF TM 5ZA|CD 5]~QFMtTD V[JF H[ zLS\'Q6 EUJFG T[ .`JZ K[4 VG[ T[ zLS\'Q6 H[ T[ VF56F >Q8N[J K[ G[ p5F;GF SZJF IMuI K[ VG[ ;J\" VJTFZGF SFZ6 K[P !_(");
Shlok.push("VG[ ;DY\" V[JF H[ zLS\'Q6 T[ H[ T[ ZFlWSFHLV[ I]ST CMI tIFZ[ ccZFWFS\'Q6cc V[J[ GFD[ HF6JF4 VG[ ~lSD6L~5 H[ ,1DL4 T[D6[ I]ST CMI tIFZ[ cc,1DLGFZFI6cc V[J[ GFD[ HF6JFP !_)");
Shlok.push("VG[ V[ zLS\'Q6 H[ T[ VH]\"G[ I]ST CMI tIFZ[ GZGFZFI6 V[J[ GFD[ HF6JF VG[ J/L T[ zLS\'Q6 H[ T[ A,EN|FlNSG[ IMU[ SZLG[ T[ T[ GFD[ SC[JFI K[ V[D HF6J]\\P !!_");
Shlok.push("VG[ V[ H[ ZFWFlNS EST T[ H[ T[ SIFZ[S TM T[ zLS\'Q6 EUJFG[G[ 50B[ CMI K[ VG[ SIFZ[S TM VlT :G[C[ SZLG[ zLS\'Q6 EUJFGGF V\\UG[ lJQF[ ZC[ K[ tIFZ[ TM T[ zLS\'Q6 EUJFG V[S,F H CMI V[D HF6JFP !!!");
Shlok.push("V[ C[T] DF8[ V[ zLS\'Q6 EUJFGGF\\ H[ :J~5 T[D6[ lJQF[ ;J[\" 5|SFZ[ SZLG[ E[N G HF6JM VG[ RT]E]\"H56\\4 VQ8E]H56\\4 ;C:+E]H56\\4 .tIFlNS H[ E[N H6FI K[ T[ TM lN=jE]H V[JF H[ T[ zLS\'Q6 T[DGL .rKFV[ SZLG[ K[ V[D HF6J]\\P !!Z");
Shlok.push("VG[ V[JF H[ T[ zLS\'Q6 EUJFG T[GL H[ ElST4 T[ H[ T[ 5\'yJLG[ lJQF[ ;J\" DG]QI4 T[D6[ SZJL VG[ T[ ElST YSL ALH]\\ S&lt;IF6SFZL ;FWG SF\\. GYL V[D HF6J]\\P !!#");
Shlok.push("VG[ lJnFlNS U]6JF/F H[ 5]~QF4 T[DGF U]6JFG56FG]\\ V[ H[ 5ZD O/ HF6J]\\4 SI]\\ TM H[ zLS\'Q6 EUJFGG[ lJQF[ ElST SZJL G[ ;t;\\U SZJM4 VG[ V[D ElST G[ ;t;\\U V[ A[ lJGF TM lJN=jFG CMI T[ 56 VWMUlTG[ 5FD[ K[P !!$");
Shlok.push("VG[ zLS\'Q6 EUJFG TYF zLS\'Q6 EUJFGGF H[ VJTFZ T[ H[ T[ wIFG SZJF IMuI K[4 TYF zLS\'Q6 EUJFGGL H[ 5|lTDF4 T[ 56 wIFG SZJF IMuI K[P DF8[ V[DG]\\ wIFG SZJ]\\P VG[ DG]QI TYF N[JFlNS H[ HLJ T[ TM zLS\'Q6 EUJFGGF EST CMI VG[ A||CDJ[tTF CMI TM 56 wIFG SZJF IMuI GYL4 DF8[ V[DG]\\ wIFG G SZJ]\\P !!5");
Shlok.push("VG[ :Y}/4 ;}1D VG[ SFZ6 v V[ H[ +6 N[C T[ YSL lJ,1F6 V[JM H[ 5MTFGM HLJFtDF4 T[G[ A|CD~5GL EFJGF SZLG[ 5KL T[ A|CD~5[ SZLG[ zLS\'Q6 EUJFGGL ElST H[ T[ ;J\" SF/G[ lJQF[ SZJLP !!&");
Shlok.push("VG[ zLDN=EFUJT 5]ZF6GM H[ NXD:S\\W T[ H[ T[ lGtI 5|tI[ VFNZ YSL ;F\\E/JM VYJF JQFM\" JQF\" V[SJFZ ;F\\E/JM VG[ H[ 5\\l0T CMI T[D6[ lGtI 5|tI[ JF\\RJM VYJF JQFM\" JQF\" V[SJFZ JF\\RJMP !!*");
Shlok.push("VG[ V[ H[ NXD:S\\W T[G]\\ H[ 5]ZxRZ6 H[ T[ 5]^I :YFGSG[ lJQF[ 5MTFGF ;FDyI\" 5|DF6[ SZJ]\\vSZFJJ]\\ VG[ J/L lJQ6];C:+GFD VFlNS H[ ;rKF:+4 T[G]\\ 5]ZxRZ6 56 5MTFGF ;FDyI\" 5|DF6[ SZJ]\\vSZFJJ]\\ T[ 5]ZxRZ6 S[J]\\ K[ TM 5MTFGF DGJF\\lKT O/G[ VF5[ V[J]\\ K[P !!(");
Shlok.push("VG[ SQ8GL N[GFZL V[JL SM. N[J ;\\A\\WL VF5NF VFJL 50[ VYJF DG]QI ;\\A\\WL VF5NF VFJL 50[ TYF ZMUFlNS VF5NF VFJL 50[ T[G[ lJQF[ H[D 5MTFGL G[ ALHFGL Z1FF YFI T[D JT\"J]\\ 56 ALHL ZLT[ G JT\"J]\\P !!)");
Shlok.push("VG[ VFRFZ4 jIJCFZ VG[ 5|FIlxRT V[ H[ +6 JFGF T[ H[ T[ N[X4 SF/4 VJ:YF4 N|jI4 HFlT VG[ ;FDyI\" V[8,FG[ VG];FZ[ SZLG[ HF6JFP !Z_");
Shlok.push("VG[ VDFZM H[ DT T[ lJlXQ8FN=J{T K[ V[D HF6J]\\4 VG[ VDG[ l5|I V[J]\\ H[ WFD T[ UM,MS K[ V[D HF6J]\\ VG[ T[ WFDG[ lJQF[ A|CD~5[ SZLG[ H[ zLS\'Q6 EUJFGGL ;[JF SZJL T[ VD[ D]lST DFGL K[ V[D HF6J]\\P !Z!");
Shlok.push("VG[ VF H[ 5}J[\" ;J[\" WD\" SCIF T[ H[ T[ VDFZF VFlzT H[ tIFUL4 U\'C:Y4 AF.vEF.4 ;J[\" ;t;\\UL T[DGF ;FDFgI WD\" SCIF K[ SC[TF\\ ;J\" ;t;\\UL DF+G[ ;ZBF 5F/JFGF K[ VG[ CJ[ V[ ;J[\"GF H[ lJX[QF WD\" K[4 T[DG[ 5\'YS 5\'YS 56[ SZLG[ SCLV[ KLV[P !ZZ");
Shlok.push("sCJ[ 5|YD WD\"J\\XL H[ VFRFI\" VG[ T[DGL 5tGLVF[ T[DGF H[ lJX[QF WD\" T[ SCLV[ KLV[Pf VDFZF DM8FEF. VG[ GFGFEF. T[DGF 5]+ H[ VIMwIF5|;FN VG[ Z3]JLZ T[D6[ 5MTFGF ;DL5 ;\\A\\W lJGFGL H[ ALHL :+LVF[ T[DG[ D\\+ p5N[X SIFZ[I G SZJMP !Z#");
Shlok.push("VG[ T[ :+LVF[G[ SIFZ[I 56 V0J]\\ GlC4 VG[ T[ ;FY[ AM,J]\\ GlC VG[ SM. HLJG[ lJQF[ S|}Z56\\ G SZJ]\\ VG[ SM.GL YF56 G ZFBJLP !Z$");
Shlok.push("VG[ jIJCFZ SFI\"G[ lJQF[ S[G]\\ 56 HDFGU~\\ G SZJ]\\ G[ SM. VF5tSF/ VFJL 50[ TM lE1FF DFULG[ 5MTFGM lGJF\"C SZLG[ T[ VF5tSF/G[ p&LT;,\\3JM4 56 SM.G]\\ SZH TM SIFZ[I G SZJ]\\P !Z5");
Shlok.push("VG[ 5MTFGF H[ lXQI4 T[D6[ WD\" lGlDtT[ 5MTFG[ VF%I]\\ H[ VgG T[ J[RJ]\\ GlC4 VG[ T[ VgG H]G]\\ YFI TM H]G]\\ SM.SG[ N.G[ GJ]\\ ,[J]\\ VG[ V[JL ZLT[ H}GFG]\\ GJ]\\ SZJ]\\ T[ J[rI]\\ G SC[JFIP !Z&");
Shlok.push("VG[ EFNZJF ;]NL RT]YL\"G[ lNJ;[ U65lTGL 5}HF SZJL VG[ VF;M JNL RT]N\"XLG[ lNJ;[ CG]DFGHLGL 5}HF SZJLP !Z*");
Shlok.push("VG[ VDFZ[ VFlzT H[ ;J[\" ;t;\\UL4 T[DGF WD\"GL Z1FF SZJFG[ VY[\" V[ ;J[\"GF U]~56FG[ lJQF[ VD[ :YF5G SIF\" V[JF H[ T[ VIMwIF5|;FN VG[ Z3]JLZ4T[D6[ D]D]1F]HGG[ NL1FF VF5JLP !Z(");
Shlok.push("VG[ 5MTFGF VFlzT H[ ;J[\" ;t;\\UL T[DG[ VlWSFZ 5|DF6[ 5MT5MTFGF WD\"G[ lJQF[ ZFBJF4 VG[ ;FW]G[ VFNZ YSL DFGJF TYF ;rKF:+GM VeIF; VFNZ YSL SZJMP !Z)");
Shlok.push("VG[ DM8F H[ D\\lNZ T[DG[ lJQF[ VD[ :YF5G SIF\" V[JF H[ zL ,1DLGFZFI6 VFlNS zLS\'Q6GF :J~54 T[DGL H[ ;[JF T[ IYFlJlWV[ SZLG[ SZJLP !#_");
Shlok.push("VG[ EUJFGGF\\ D\\lNZ 5|tI[ VFjIM H[ CZSM. VgGFYL\" DG]QI4 T[GL 5MTFGF ;FDyI\" 5|DF6[ VgGGF NFG[ SZLG[ VFNZYSL ;\\EFJGF SZJLP !#!");
Shlok.push("VG[ lJnFYL\" E6FjIFGL XF/F SZFJLG[ 5KL T[DF\\ V[S lJN=FG A|FCD6G[ ZFBLG[ 5\'yJLG[ lJQF[ ;lN=JmFGL 5|J\'ltT SZFJJL4 S[D H[ lJnFNFG[ SZLG[ DM8]\\ 5]^I YFI K[P !#Z");
Shlok.push("VG[ CJ[ V[ VIMwIF5|;FN VG[ Z3]JLZ V[ A[GL H[ 5tGLVF[ T[D6[ 5MT5MTFGF 5lTGL VF7FV[ SZLG[ :+LVF[G[ H zLS\'Q6GF D\\+GM p5N[X SZJM 56 5]~QFG[ G SZJMP !##");
Shlok.push("VG[ J/L T[ A[ H6GL H[ 5tGLVF[ T[D6[ 5MTFGF ;DL5 ;\\A\\W lJGFGF H[ 5]~QF T[DGM :5X\" SIFZ[I G SZJM4 VG[ T[DGL ;FY[ AM,J]\\ GlC4 G[ V[DG[ 5MTFG]\\ D]B 56 G N[BF0J]\\P sV[JL ZLT[ WD\"J\\XL VFRFI\" VG[ T[DGL 5tGLVM T[DGF H[ lJX[QF WD\" T[ SCIFP !#$");
Shlok.push("sCJ[ U\'C:YFzDLGF H[ lJX[QF WD\" K[ T[ SCLV[ KLV[Pf VDFZ[ VFlzT H[ U\'C:YFzDL 5]~QF T[D6[ 5MTFGF ;DL5 ;\\A\\W lJGFGL H[ lJWJF :+LVF[ T[DGM :5X\" G SZJMP !#5");
Shlok.push("VG[ T[ U\'C:YFzDL 5]~QF T[D6[ I]JFG VJ:YFV[ I]ST V[JL H[ 5MTFGL DF4 AC[G VG[ lNSZL T[ ;\\UFY[ 56 VF5tSF/ lJGF V[SF\\T :Y/G[ lJQF[ G ZC[J]\\4 VG[ 5MTFGL :+LG]\\ NFG SM.G[ G SZJ]\\P !#&");
Shlok.push("VG[ H[ :+LG[ SM. 5|SFZGF jIJCFZ[ SZLG[ ZFHFGM 5|;\\U CMI T[JL :+LGM H[ 5|;\\U T[ SM. 5|SFZ[ 56 G H SZJMP !#*");
Shlok.push("VG[ U\'C:YFzDL T[D6[ 5MTFG[ 3[Z VFjIM H[ VlTlY T[G[ 5MTFGF ;FDyI\" 5|DF6[ VgGFlNS[ SZLG[ 5}HJM4 VG[ J/L CMDFlNS H[ N[JSD\" VG[ zFwWFlNS H[ l5T\'SD\" T[ H[ T[ 5MTFGF ;FDyI\" 5|DF6[ IYFlJlW H[D 38[ T[D SZJ]\\P !#(");
Shlok.push("VG[ VDFZF VFlzT H[ U\'C:Y T[D6[ DFTFvl5TF VG[ U]~ TYF ZMUFT]Z V[JF H[ SM. DG]QI T[DGL H[ ;[JF T[ HLJG5I\"\\T 5MTFGF ;FDyI\" 5|DF6[ SZJLP !#)");
Shlok.push("VG[ J/L 5MTFGF J6F\"zDG[ 3l8T V[JM H[ pnD T[ 5MTFGF ;FDyI\" 5|DF6[ SZJM4 VG[ S\'lQFJ\'ltTJF/F H[ U\'C:Y ;t;\\UL T[D6[ A/lNIFGF J\'QF6GM prK[N G SZJMP !$_");
Shlok.push("VG[ T[ U\'C:Y ;t;\\UL T[D6[ 5MTFGF ;FDyI\" 5|DF6[ ;DIG[ VG];ZLG[ H[8,M 5MTFGF 3ZDF\\ JZM CMI4 T[8,F VgG N|jIGM ;\\U|C H[ T[ SZJM4 VG[ H[GF 3ZDF\\ 5X] CMI V[JF H[ U\'C:Y T[D6[ 5MTFGF ;FDyI\" 5|DF6[ RFI\" 5}/FGM ;\\U|C SZJMP !$!");
Shlok.push("VG[ UFI4 A/N4 E[\\;4 3M0F VFlNS H[ 5X] T[DGL T\'6 H/FlNS[ SZLG[ 5MTFJT[ HM ;\\EFJGF YFI TM T[ 5X]G[ ZFBJF VG[ HM ;\\EFJGF G YFI TM G ZFBJFP !$Z");
Shlok.push("VG[ ;F1FLV[ ;lCT ,BT SIF\" lJGF TM 5MTFGF 5]+ VG[ lD+FlNS ;FY[ 56 5\'yJL G[ WGGF ,[6N[6[ SZLG[ jIJCFZ H[ T[ SIFZ[I G SZJMP !$#");
Shlok.push("VG[ 5MTFG]\\ VYJF ALHFG]\\ H[ lJJFC ;\\A\\WL SFI\" T[G[ lJQF[4 VF5JF IMuI H[ WG4 T[G]\\ ;F1FLV[ ;lCT ,BT SIF\" lJGF S[J/ AM,L H G SZJLP !$$");
Shlok.push("VG[ 5MTFGL p5HG]\\ H[ N|jI T[G[ VG];FZ[ lGZ\\TZ BR\" SZJM4 56 T[ p5ZF\\T G SZJM VG[ H[ p5H SZTF\\ JWFZ[ BR\" SZ[ K[ T[G[ DM8]\\ N]oB YFI K[ V[D ;J\" U\'C:YMV[ DGDF\\ HF6J]\\P !$5");
Shlok.push("VG[ 5MTFGF jIJCFZSFI\"G[ lJQF[ H[8,F WGGL p5H CMI TYF H[8,M BR\" CMI4 T[ A[IG[ ;\\EFZLG[ lGtI 5|tI[ ~0F V1FZ[ SZLG[ 5MT[ T[G]\\ GFD]\\ ,BJ]\\P !$&");
Shlok.push("VG[ T[ U\'C:YFzDL ;t;\\UL T[D6[ 5MTFGL H[ J\'ltT VG[ pnD4 T[ YSL 5FdI]\\ H[ WGWFgIFlNS4 T[ YSL NXDM EFU SF-LG[ zLS\'Q6 EUJFGG[ V5\"6 SZJMP VG[ H[ jIJCFZ[ N]A\"/ CMI T[D6[ lJXDM EFU V5\"6 SZJMP !$*");
Shlok.push("VG[ V[SFNXL VFlNS H[ J|T T[DG]\\ H[ pnF5G T[ H[ T[ 5MTFGF ;FDyI\" 5|DF6[ IYFXF:+ SZJ]\\P T[ pnF5G S[J]\\ K[4 TM DGJF\\lKT O/G]\\ VF5GFZ]\\ K[P !$(");
Shlok.push("VG[ zFJ6 DF;G[ lJQF[ zLDCFN[JG]\\ 5}HG4 H[ T[ lA&lt;J5+FlNS[ SZLG[ 5|LlT5}J\"S ;J\" 5|SFZ[ 5MT[ SZJ]\\ VYJF ALHF 5F;[ SZFJJ]\\P !$)");
Shlok.push("VG[ 5MTFGF H[ VFRFI\" T[ YSL TYF zLS\'Q6 EUJFGGF H[ D\\lNZ4 T[YSL SZH G SF-J]\\4 VG[ J/L T[ 5MTFGF VFRFI\" YSL VG[ zLS\'Q6GF D\\lNZ YSL 5MTFGF jIJCFZG[ VY[\" 5F+4 3Z[6F\\ VG[ J:+FlNS H[ J:T] T[ DFUL ,FJJF GlCP !5_");
Shlok.push("VG[ zLS\'Q6 EUJFG TYF 5MTFGF U]~ TYF ;FW] T[DGF NX\"G SZJFG[ VY[\" UI[ ;T[ DFU\"G[ lJQF[ 5FZS]\\ VgG BFJ]\\ GlC4 TYF zLS\'Q6 EUJFG TYF 5MTFGF U]~ TYF ;FW] T[DGF H[ :YFGS T[DG[ lJQF[ 56 5FZS]\\ VgG BFJ]\\ GlC S[D H[ T[ 5FZS]\\ VgG TM 5MTFGF 5]^IG[ CZL,[ V[J]\\ K[4 DF8[ 5MTFGL UF\\9G]\\ BZR BFJ]\\P !5!");
Shlok.push("VG[ 5MTFGF SFDSFH SZJF T[0IF H[ DH]Z T[DG[ H[8,]\\ WG VYJF WFgI NLWFG]\\ SCI]\\ CMI T[ 5|DF6[ H VF5J]\\ 56 T[DF\\YL VF[K]\\ G VF5J]\\ VG[ 5MTF5F;[ SM. SZH DF\\UTM CMI G[ T[ SZH N. R]SIF CM.V[ T[ JFTG[ KFGL G ZFBJL4 TYF 5MTFGM J\\X TYF SgIFNFG V[ 56 KFG]\\ G ZFBJ]\\4 VG[ N]Q8 V[JF H[ HG T[DGL ;FY[ jIJCFZ G SZJMP !5Z");
Shlok.push("VG[ H[ 9[SF6[ 5MT[ ZC[TF CM.V[ T[ 9[SF6[ SM.S S96 E}\\0M SF/ VYJF X+] VYJF ZFHF T[GF p5N=J[ SZLG[ ;J\" 5|SFZ[ 5MTFGL ,FH HTL CMI S[ WGGM GFX YTM CMI4 S[ 5MTFGF 5|F6GM GFX YTM CMIP !5#");
Shlok.push("VG[ T[ HM 5MTFGF D}/ UZF;G]\\ TYF JTGG]\\ UFD CMI4 TM 56 T[GM lJJ[SL V[JF H[ VDFZF ;t;\\UL U\'C:Y T[D6[ TtSF/ tIFU SZL N[JM VG[ HIF\\ p5N-J G CMI4 T[JM H[ ALHM N[X T[ 5|tI[ H.G[ ;]B[YL ZC[J]\\P !5$");
Shlok.push("VG[ WGF-I V[JF H[ U\'C:Y ;t;\\UL T[D6[ lC\\;FV[ ZlCT V[JF H[ lJQ6 ;\\A\\WL I7 T[ SZJF TYF TLY\"G[ lJQF[ TYF N=JFNXL VFlN 5J\"G[ lJQF[ A|FCD6 TYF ;FW] T[DG[ HDF0JFP !55");
Shlok.push("VG[ WGF-I V[JF H[ U\'C:Y ;t;\\UL T[D6[ EUJFGGF D\\lNZG[ lJQF[ DM8F pt;J SZFJJF4 TYF ;]5F+ V[JF H[ A|FCD6 T[DG[ GFGF 5|SFZGF NFG N[JFP !5&");
Shlok.push("VG[ VDFZF VFlzT V[JF H[ ;t;\\UL ZFHF T[D6[ WD\"XF:+G[ VFXZLG[ 5MTFGF 5]+GL 5[9[ 5MTFGL 5|HFG]\\ 5F,G SZJ]\\4 VG[ 5\'yJLG[ lJQF[ WD\"G]\\ :YF5G SZJ]\\P !5*");
Shlok.push("VG[ T[ ZFHF T[D6[ ZFHIGF H[ ;FT V\\U TYF RFZ p5FI TYF K U]6 T[ H[ T[ ,1FG[ SZLG[ IYFY\"56[ HF6JF4 VG[ TLY\" H[ RFZ DMS&lt;IF\\GF :YFGS TYF jIJCFZGF HF6GFZF H[ ;EF;N TYF N\\0JF IMuI H[ DF6; TYF N\\0JF IMuI GlC V[JF H[ DF6; V[ ;J\"G[ ,1F6[ SZLG[ IYFY\"56[ HF6JFP !5(");
Shlok.push("sCJ[ ;]JFl;GL AF.VF[GF lJX[QF WD\" T[ SCLV[ KLV[f VDFZ[ VFlzT H[ ;]JFl;GL AF.VF[ T[D6[ 5MTFGM 5lT V\\W CMI4 ZMUL CMI4 NlZN|L CMI4 G5]\\;S CMI4 TM 56 T[G[ .`JZGL 5[9[ ;[JJM4 VG[ 5lT 5|tI[ S8] JRG G AM,J]\\P !5)");
Shlok.push("VG[ T[ ;]JFl;GL :+LVF[ T[D6[ ~5 VG[ IF{JG T[6[ I]ST VG[ U]6JFG V[JM H[ VgI 5]~QF T[GM 5|;\\U ;CH :JEFJ[ 56 G H SZJMP !&_");
Shlok.push("VG[ 5lTJ|TF V[JL H[ ;]JFl;GL :+LVF[ T[D6[ 5MTFGL GFEL4 ;FY/ VG[ KFTL T[G[ ALHM 5]~QF N[B[ V[D G JT\"J]\\4 VG[ VF[-IFGF J:+ lJGF p3F0[ XZLZ[ G ZC[J]\\4 VG[ EF\\0 EJF. HMJF G HJ]\\4 VG[ lG,\"HH V[JL H[ :+LVM TYF :J{lZ6L4 SFlDGL VG[ 5]\\xR,L V[JL H[ :+LVM T[DGM ;\\U G SZJMP !&!");
Shlok.push("VG[ ;]JFl;GL  :+LVF[ T[D6[ 5MTFGM 5lT 5ZN[X UI[ ;T[ VFE}QF6 G WFZJF4 G[ ~0F\\ J:+ G 5C[ZJF\\4 VG[ 5FZS[ 3[Z A[;JF G HJ]\\ VG[ CF:I lJGMNFlNSGM tIFU SZJMP !&Z");
Shlok.push("sCJ[ lJWJF :+LVF[GF lJX[QF WD\" T[ SCLV[ KLV[Pf VDFZ[ VFlzT H[ lJWJF :+LVF[ T[D6[ TM 5lT A]lwWV[ SZLG[ zLS\'Q6 EUJFGG[ ;[JJF4 VG[ 5MTFGF l5TF4 5]+FlNS H[ ;\\A\\WL T[DGL VF7FG[ lJQF[ JT\"J]\\4 56 :JT\\+56[ G JT\"J]\\P !&#");
Shlok.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF ;DL5 ;\\A\\W lJGFGF H[ 5]~QF T[DGM :5X\" SIFZ[I G SZJM4 VG[ 5MTFGL I]JFJ:YFG[ lJQF[ VJxI SFI\" lJGF ;DL5 ;\\A\\W lJGFGF H[ I]JFG 5]~QF T[DGL ;FY[ SIFZ[I 56 AM,J]\\ GlCP !&$");
Shlok.push("VG[ WFJ6M H[ AF/S T[GF :5X\"G[ lJQF[ TM H[D 5X]G[ V0L HJFI VG[ NMQF GYL T[D NMQF GYL4 VG[ SM. VJxIG]\\ SFDSFH 50[ T[G[ lJQF[ SM.S J\'wW 5]~QFG[ V0L HJFI4 TYF T[ J\'wW ;FY[ AM,FI T[G[ lJQF[ NMQF GYLP !&5");
Shlok.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF ;DL5 ;\\A\\W lJGFGF H[ 5]~QF T[ YSL SM.56 lJnF G E6JL4 VG[ J|T p5JF;[ SZLG[ JFZ\\JFZ 5MTFGF N[CG]\\ NDG SZJ]\\P !&&");
Shlok.push("VG[ T[ lJWJF :+LVF[ T[D6[ 5MTFGF 3ZDF\\ 5MTFGF HLJG5I\"\\T N[ClGJF\"C YFI V[8,]\\ H HM WG CMI TM T[ WG H[ T[ WD\"SFI\"G[ lJQF[ 56 G VF5J]\\ VG[ HM T[YL VlWS CMI TM VF5J]\\P !&*");
Shlok.push("VG[ lJWJF :+LVF[ T[D6[ V[SJFZ VFCFZ SZJM4 VG[ 5\'yJLG[ lJQF[ ;}J]\\4 VG[ D{Y]GF;ST V[JF H[ 5X] 51FL VFlNS HLJ 5|F6LDF+ T[DG[ SIFZ[I HF6LG[ HMJF\\ GlCP !&(");
Shlok.push("VG[ T[ lJWJF :+LVF[ T[D6[ ;]JFl;GL :+LGF H[JM J[QF G WFZJM4 TYF ;\\gIF;6L TYF J[ZFU6L T[GF H[JM J[QF G WFZJM4 VG[ 5MTFGF N[X4 S]/ VG[ VFRFZ T[G[ lJ~wW V[JM H[ J[QF T[ 56 SIFZ[I G WFZJMP !&)");
Shlok.push("VG[ UE\"GL 5F0GFZL H[ :+L T[GM ;\\U G SZJM4 G[ T[GM :5X\" 56 G SZJM4 VG[ 5]~QFGF X\'\\UFZZ; ;\\A\\WL H[ JFTF\" T[ SIFZ[I G SZJL4 VG[ G ;F\\E/JLP !*_");
Shlok.push("VG[ I]JF VJ:YFG[ lJQF[ ZCL V[JL H[ lJWJF :+LVF[ T[D6[ I]JF VJ:YFJF/F H[ 5MTFGF ;\\A\\WL 5]~QF T[DGL ;\\UFY[ 56 V[SF\\T:Y/G[ lJQF[ VF5tSF/ 50IF lJGF G ZC[J]\\P !*!");
Shlok.push("VG[ CM/LGL ZDT G SZJL4 VG[ VFE}QF6FlNSG]\\  WFZ6 G SZJ]\\4 VG[ ;]J6F\"lNS WFT]GF TFZ[ I]ST V[JF H[ hL6F\\ J:+ T[G]\\ WFZ6 56 SIFZ[I G SZJ]\\P !*Z");
Shlok.push("VG[ ;]JFl;GL G[ lJWJF V[JL H[ :+LVF[ T[D6[ J:+ 5C[IF\" lJGF gCFJ]\\ GlC4 VG[ 5MTFG]\\ H[ ZH:J,F56\\  T[ SM. 5|SFZ[ U]~ G ZFBJ]\\P !*#");
Shlok.push("VG[ J/L ZH:J,F V[JL H[ ;]JFl;GL VG[ lJWJF :+LVF[ T[ +6 lNJ; ;]WL SM. DG]QIG[ TYF J:+FlNSG[ V0[ GlC4 VG[ RMY[ lNJ;[ GFCLG[ V0J]\\P sV[JL ZLT[ U\'C:YFzDL V[JF H[ 5]~QF VG[ :+LVF[ T[DGF H[ VF lJX[QF WD\" SCIF T[ ;J[\" WD\"J\\XL VFRFI\" VG[ T[DGL 5tGLVM T[D6[ 56 5F/JF4 S[D S[ V[ U\'C:Y K[Pf !*$");
Shlok.push("CJ[ G{lQ9S A|CDRFZLGF H[ lJX[QF WD\" T[ SCLV[ KLV[P VDFZ[ VFlzT V[JF H[ G{lQ9S A|CDRFZL T[D6[ :+L DF+GM :5X\" G SZJM4 VG[ :+LVF[ ;\\UFY[ AM,J]\\ GlC4 VG[ HF6LG[ T[ :+LVF[ ;gD]B HMJ]\\ GlCP !*5");
Shlok.push("VG[ T[ :+LVF[GL JFTF\" SIFZ[I G SZJL VG[ G ;F\\E/JL4 VG[ H[ :YFGSG[ lJQF[ :+LVF[GM 5UO[Z CMI4 T[ :YFGSG[ lJQF[ :GFGFlNS lS|IF SZJF G HJ]\\P !*&");
Shlok.push("VG[ N[JTFGL 5|lTDF lJGF ALHL H[ :+LGL 5|lTDF4 lR+GL VYJF SFQ9FlNSGL CMI T[GM :5X\" G SZJM4 VG[ HF6LG[ TM T[ 5|lTDFG[ HMJL 56 GlCP !**");
Shlok.push("VG[ T[ G{LQ9S A|CDRFZL T[D6[ :+LGL 5|lTDF G SZJL4 VG[ :+LV[ 5MTFGF XZLZ p5Z WFZ[,]\\ H[ J:+ T[G[ V0J]\\ GlC4 VG[ D{Y]GF;ST V[JF\\ H[ 5X]v51FL VFlNS 5|F6LDF+4 T[DG[ HF6LG[ HMJF GlCP !*(");
Shlok.push("VG[ :+LGF J[XG[ WZL ZCIFM V[JM H[ 5]~QF T[G[ V0J]\\ GlC VG[ T[GL ;FD]\\ HMJ]\\ GlC4 VG[ T[ ;FY[ AM,J]\\ GlC VG[ :+LGM pN=N[X SZLG[ EUJFGGL SYF4 JFTF\"4 SLT\"G 56 G SZJFP !*)");
Shlok.push("VG[ T[ G{lQ9S A|CDRFZL4 T[D6[ 5MTFGF A|CDRI\" J|TGM tIFU YFI4 V[J]\\ H[ ;tI JRG T[ TM 5MTFGF U]~G]\\ 56 G DFGJ]\\4 G[ ;NFSF/ WLZHJFG ZC[J]\\ VG[ ;\\TMQF[ I]ST ZC[J]\\ G[ DFG[ ZlCT ZC[J]\\P !(_");
Shlok.push("VG[ A/FtSFZ[ SZLG[ 5MTFG[ VlTXI ;DL5[ VFJTL V[JL H[ :+L T[G[ AM,LG[ VYJF lTZ:SFZ SZLG[ 56 T]ZT JFZJL4 56 ;DL5[ VFJJF N[JL GlCP !(!");
Shlok.push("VG[ HM SIFZ[S :+LVF[GM VYJF 5MTFGM 5|F6 GFX YFI4 V[JM VF5tSF/ VFJL 50[4 tIFZ[ TM T[ :+LVF[G[ V0LG[ VYJF T[ ;FY[ AM,LG[ 56 T[ :+LVF[GL Z1FF SZJL VG[ 5MTFGL 56 Z1FF SZJLP !(Z");
Shlok.push("VG[ T[ G{lQ9S A|CDRFZL T[D6[ 5MTFG[ XZLZ[ T{,DN\"G G SZJ]\\ G[ VFI]W G WFZJ]\\4 G[ EI\\SZ V[JM H[ J[QF T[ G WFZJM VG[ Z;GF >lgN|IG[ HLTJLP !(#");
Shlok.push("VG[ H[ A|FCD6GF 3ZG[ lJQF[ :+L 5LZ;GFZL CMI4 T[G[ 3[Z lE1FF SZJF HJ]\\ GlC G[ HIF\\ 5]~QF 5LZ;GFZM CMI tIF\\ HJ]\\P !($");
Shlok.push("VG[ T[ G{lQ9S A|CDRFZL4 T[D6[ J[NXF:+GM VeIF; SZJM G[ U]~GL ;[JF SZJL4 G[ :+LVF[GL 5[9[ H :+{6 5]~QFGM ;\\U4 H[ T[ ;J\"SF/[ JH\"JMP !(5");
Shlok.push("VG[ HFlTV[ SZLG[ H[ A|FCD6 CMI4 T[ SM.V[ 56 RD\"JFlZ G 5LJ]\\ G[ 0]\\U/L G[ ,;6 VFlNS H[ VE1I J:T] T[ A|FCD6 HFlT CMI T[6[ SM. 5|SFZ[ G BFJLP !(&");
Shlok.push("VG[ H[ A|FCD6 CMI T[G[ :GFG4 ;\\wIF UFI+LGM H54 zLlJQ6GL 5}HF VG[ J{`JN[J V[8,F JFGF SIF\" lJGF EMHG SZJ]\\ H GlCP sV[JL ZLT[ G{lQ9S A|CDRFZLGF lJX[QF WD\" SCIFPf !(*");
Shlok.push("CJ[ ;FW]GF H[ lJX[QF WD\" T[ SCLV[ KLV[4 VDFZ[ VFlzT H[ ;J[\" ;FW] T[D6[ G{lQ9S A|CDRFZLGL 5[9[ :+LVF[GF\\ NX\"GvEFQF6FlNS 5|;\\UGM tIFU SZJM TYF :+{6 5]~QFGF 5|;\\UFlNSGM tIFU SZJM4 VG[ V\\ToX+] H[ SFD4 S|MW4 ,ME VG[ DFG VFlNS T[DG[ HLTJFP !((");
Shlok.push("VG[ ;J[\" H[ >lgN|IM T[ HLTJL G[ Z;GF >lgN|IG[ TM lJX[QF[ SZLG[ HLTJL4 VG[ N|jIGM ;\\U|C 5MT[ SZJM GlC G[ SM. ALHF 5F;[ 56 SZFJJM GlCP !()");
Shlok.push("VG[ SM.GL YF56 G ZFBJL VG[ SIFZ[I 56 WLZHTFGM tIFU G SZJM VG[ 5MTFGF pTFZFGL HFIUF A\\lWGL CMI TM T[G[ lJQF[ SIFZ[I :+LGM 5|J[X YJF N[JM GlCP !)_");
Shlok.push("VG[ T[ ;FW] T[D6[4 VF5tSF/ 50IF lJGF ZF+LG[ lJQF[ ;\\3;MAT lJGFG]\\ RF,J]\\ GlC TYF VF5tSF/ 50IF lJGF SIFZ[I 56 V[S,F RF,J]\\ GlCP !)!");
Shlok.push("VG[ H[ J:+ AC] D}&lt;IJF/]\\ CMI TYF lR+ lJlR+ EFTG]\\ CMI4 TYF S;]\\AFlNS H[ Z\\U T[6[ SZLG[ Z\\U[,]\\ CMI TYF XF,vN]XF,F CMI G[ T[ HM ALHFGL .rKFV[ SZLG[ 5MTFG[ 5|F%T YI]\\ CMI4 TM 56 T[ J:+ 5MTFG[ 5C[ZJ]\\ VM-J]\\ GlCP !)Z");
Shlok.push("VG[ lE1FF TYF ;EF 5|;\\U V[ A[ SFI\" lJGF U\'C:YGF 3Z 5|tI[ HJ]\\ GlC4 VG[ EUJFGGL H[ GJ 5|SFZGL ElST T[ lJGF jIY\" SF/ lGU\"DJM GlC4 lGZ\\TZ ElST SZLG[ H SF/ lGU\"DJMP !)#");
Shlok.push("VG[ H[ U\'C:YGF 3ZG[ lJQF[ ZF\\W[, VgGGM 5LZ;GFZM 5]~QF H CMI TYF :+LVF[GM NX\"GFlNS 5|;\\U SM. ZLT[ YFI V[D G CMIP !)$");
Shlok.push("T[JL ZLTG]\\ H[ U\'C:YG]\\ 3Z T[ 5|tI[ VDFZF ;FW] T[D6[ HDJF HJ]\\ VG[ V[ SCIF]\\ T[J]\\ G CMI TM SFR]\\ VgG DFULG[ 5MTFGF CFY[ Z;M. SZJL G[ EUJFGG[ G{J[n WZLG[ HDJ]\\P !)5");
Shlok.push("VG[ 5}J[\" kQFEN[J EUJFGGF 5]+ H[ EZTHL T[ H[ T[ 5\'yJLG[ lJQF[ H0 A|FCD6 YSF H[D JT\"TF CJF T[D H 5ZDC\\; V[JF H[ VDFZF ;FW] T[D6[ JT\"J]\\P !)&");
Shlok.push("VG[ G{lQ9S A|CDRFZLG[ V[ ;FW] T[D6[ TF\\A], TYF VOL6 TYF TDFS] .tIFlNSG]\\ H[ E1F6 T[ HTG[ SZLG[ JH\"J]\\P !)*");
Shlok.push("VG[ T[ G{lQ9S A|CDRFZL G[ ;FW] T[D6[ UEF\"WFG VFlNS H[ ;\\:SFZ T[DG[ lJQF[ HDJ]\\ GlC TYF V[SFNXFC 5I\"\\T H[ 5|[TzFwW T[DG[ lJQF[ HDJ]\\ GlC TYF N=JFNXFC zFwWG[ lJQF[ HDJ]\\ GlCP !)(");
Shlok.push("VG[ ZMUFlNS VF5tSF/ 50IF lJGF lNJ;[ ;]J]\\ GlC VG[ U|FdIJFTF\" SZJL GlC G[ HF6LG[ ;F\\E/JL GlCP !))");
Shlok.push("VG[ T[ G{lQ9S A|CDRFZL G[ ;FW] T[D6[ ZMUFlNS VF5tSF/ 50IF lJGF BF8,F p5Z ;}J]\\ GlC4 VG[ ;FW]GL VFU/ TM lGZ\\TZ lGQS5856[ JT\"J]\\P Z__");
Shlok.push("VG[ T[ ;FW] VG[ A|CDRFZL T[D6[ SM.S S]DlTJF/F N]Q8 HG CMI4 G[ T[ 5MTFG[ UF/ N[ VYJF DFZ[ TM T[ ;CG H SZJ]\\4 56 T[G[ ;FDL UF/ G N[JL G[ DFZJM GlC4 VG[ T[G]\\ H[D lCT YFI T[DH DGDF\\ lR\\TJG SZJ]\\4 56 T[G]\\ E]\\0]\\ YFI V[JM TM ;\\S&lt;5 56 G SZJMP Z_!");
Shlok.push("VG[ SM.G]\\ N}T56\\ G SZJ]\\ TYF RFl0IF56\\ G SZJ]\\ G[ SM.GF RFZR1F] G YJ]\\ VG[ N[CG[ lJQF[ VC\\A]lwW G SZJL G[ :JHGFlNSG[ lJQF[ DDTF G SZJLP sV[JL ZLT[ ;FW]GF lJX[QF WD\" SCIFF\\Pf Z_Z");
Shlok.push("VG[ VDFZ[ VFlzT V[JF H[ ;t;\\UL AF. EF. ;J[\" T[DGF H[ ;FDFgI WD\" VG[ lJX[QF WD\" T[ H[ T[ ;\\1F[5[ SZLG[ VFJL ZLT[ VD[ ,bIF K[ VG[ VF WD\"GM H[ lJ:TFZ T[ TM VDFZF ;\\5|NFIGF H[ U|\\Y T[ YSL HF6JMP Z_#");
Shlok.push("VG[ ;J[\" H[ ;rKF:+ T[GM H[ ;FZ T[G[ VD[ VDFZL A]lwWV[ SZLG[ pwWFZLG[ VF lX1FF5+L H[ T[ ,BL K[ T[ S[JL K[ v TM ;J[\" DG]QIDF+G[ DGJF\\lKT O/GL N[GFZL K[P Z_$");
Shlok.push("V[ C[T] DF8[ VDFZF VFlzT H[ ;J[\" ;t;\\UL T[D6[ ;FJWFG56[ SZLG[ lGtI5|tI[ VF lX1FF5+LG[ VG];ZLG[ H JT\"J]\\P 56 5MTFGF DGG[ HF6[ TM SIFZ[I G JT\"J]\\P Z_5");
Shlok.push("VG[ H[ VDFZF VFlzT 5]~QF G[ :+LVF[ T[ H[ T[ lX1FF5+L 5|DF6[ JT\"X[4 T[ TM WD\"4VY\"4 SFD G[ DM1F V[ RFZ 5]~QFFY\"GL l;lwWG[ lGxRI 5FDX[P Z_&");
Shlok.push("VG[ H[ AF.vEF.4 VF lX1FF5+L 5|DF6[ GlC JT[\" T[ TM VDFZF ;\\5|NFI YSL AFC[Z K[ V[D VDFZF ;\\5|NFIJF/F :+Lv5]~QF T[D6[ HF6J]\\P Z_*");
Shlok.push("VG[ VDFZF H[ VFlzT ;t;\\UL T[D6[ VF lX1FF5+LGM lGtI5|tI[ 5F9 SZJM VG[ H[G[ E6TF VFJ0T]\\ G CMI T[D6[ TM VFNZ YSL VF lX1FF5+LG]\\ zJ6 SZJ]\\P Z_(");
Shlok.push("VG[ VF lX1FF5+LG[ JF\\RL ;\\E/FJ[ V[JM SM. G CMI tIFZ[ TM lGtI5|tI[ VF lX1FF5+LGL 5}HF SZJL4 VG[ VF H[ VDFZL JF6L T[ VDF~\\ :J~5 K[P V[ ZLT[ 5ZD VFNZ YSL DFGJLP Z_)");
Shlok.push("VG[ VF H[ VDFZL lX1FF5+L K[ T[ H[ T[ N{JL;\\5NFV[ SZLG[ I]ST V[JM H[ HG CMI4 T[G[ VF5JL VG[ H[ HG VF;]ZL ;\\5NFV[ SZLG[ I]ST CMI4 T[G[ TM SIFZ[I G VF5JLP Z!_");
Shlok.push(";\\JT !((Z V-FZ;M aIF;LGF DCF;]NL 5\\RDLG[ lNJ;[ VF lX1FF5+L VD[ ,BL K[4 T[ 5ZD S&lt;IF6SFZL K[P Z!!");
Shlok.push("VG[ 5MTFGF VFlzT H[ ESTHG T[DGL H[ ;DU| 5L0F T[GF\\ GFX SZGFZF V[JF G[ WD[\" ;lCT H[ ElST T[GL Z1FFGF SZGFZF V[JF G[ 5MTFGF ESTHGG[ DGJF\\lKT ;]BGF VF5GFZF V[JF H[ zLS\'Q6 EUJFG4 T[ H[ T[ VDFZF ;DU| D\\U,G[ lJ:TFZMP Z!Z <br /></br> >lT zL ;CHFG\\N :JFDL lXQI lGtIFG\\N D]lG l,lBTF lX1FF5+L 8LSF ;DF%TF");


var ShlokNumbers = ["!", "Z", "#", "$", "5", "&", "*", "(", ")", "!_", "!!", "!Z", "!#", "!$", "!5", "!&", "!*", "!(", "!)", "Z_", "Z!", "ZZ", "Z#","Z$", "Z5"];
ShlokNumbers.push("Z&", "Z*", "Z(", "Z0", "#_", "#!", "#Z", "##", "#$", "#5", "#&", "#*", "#(", "#)", "$_", "$!", "$Z", "$#", "$$", "$5", "$&", "$*", "$(", "$)", "5_");
ShlokNumbers.push("5!", "5Z", "5#", "5$", "55", "5&", "5*", "5(", "5)", "&_", "&!", "&Z", "&#", "&$", "&5", "&&", "&*", "&(", "&)", "*_", "*!", "*Z", "*#", "*$", "*5");
ShlokNumbers.push("*&", "**", "*(", "*)", "(_", "(!", "(Z", "(#", "($", "(5", "(&", "(*", "((", "()", ")_", ")!", ")Z", ")#", ")$", ")5", ")&", ")*", ")(", "))", "!__");
ShlokNumbers.push("!_!", "!_Z", "!_#", "!_$", "!_5", "!_&", "!_*", "!_(", "!_)", "!!_", "!!!", "!!Z", "!!#", "!!$", "!!5", "!!&", "!!*", "!!(", "!!)", "!Z_", "!Z!", "!ZZ", "!Z#", "!Z$", "1Z5");
ShlokNumbers.push("!Z&", "!Z*", "!Z(", "!Z)", "!#_", "!#!", "!#Z", "!##", "!#$", "!#5", "!#&", "!#*", "!#(", "!#)", "!$_", "!$!", "!$Z", "!$#", "!$$", "!$5", "!$&", "!$*", "!$(", "!$)", "!5_");
ShlokNumbers.push("!5!", "!5Z", "!5#", "!5$", "!55", "!5&", "!5*", "!5(", "!5)", "!&_", "!&!", "!&Z", "!&#", "!&$", "!&5", "!&&", "!&*", "!&(", "!&)", "!*_", "!*!", "!*Z", "!*#", "!*$", "!*5");
ShlokNumbers.push("!*&", "!**", "!*(", "!*)", "!(_", "!(!", "!(Z", "!(#", "!($", "!(5", "!(&", "!(*", "!((", "!()", "!)_", "!)!", "!)Z", "!)#", "!)$", "!)5", "!)&", "!)*", "!)(", "!))", "Z__");
ShlokNumbers.push("Z_!", "Z_Z", "Z_#", "Z_$", "Z_5", "Z_&", "Z_*", "Z_(", "Z_)", "Z!_", "Z!!", "Z!Z");